# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Tue May 12 22:24:31 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design ECC_Cache_System

create_clock -name "clk" -period 10.0 -waveform {0.0 5.0} [get_ports clk]
set_load -pin_load 0.05 [get_ports {data_out[8]}]
set_load -pin_load 0.05 [get_ports {data_out[9]}]
set_load -pin_load 0.05 [get_ports {data_out[10]}]
set_load -pin_load 0.05 [get_ports {data_out[11]}]
set_load -pin_load 0.05 [get_ports {data_out[12]}]
set_load -pin_load 0.05 [get_ports {data_out[13]}]
set_load -pin_load 0.05 [get_ports {data_out[14]}]
set_load -pin_load 0.05 [get_ports {data_out[15]}]
set_load -pin_load 0.05 [get_ports {data_out[16]}]
set_load -pin_load 0.05 [get_ports {data_out[17]}]
set_load -pin_load 0.05 [get_ports {data_out[18]}]
set_load -pin_load 0.05 [get_ports {data_out[19]}]
set_load -pin_load 0.05 [get_ports {data_out[20]}]
set_load -pin_load 0.05 [get_ports {data_out[21]}]
set_load -pin_load 0.05 [get_ports {data_out[22]}]
set_load -pin_load 0.05 [get_ports {data_out[23]}]
set_load -pin_load 0.05 [get_ports hit]
set_false_path -from [get_ports rst]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports rst]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports write_en]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports read_en]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_in[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {address[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {address[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {address[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {address[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {address[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {address[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[9]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[10]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[11]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[12]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[13]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[14]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[15]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[16]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[17]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[18]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[19]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[20]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[21]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[22]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {codeword_received[23]}]
set_input_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports display_enable]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[16]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[17]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[18]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[19]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[20]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[21]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[22]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports {data_out[23]}]
set_output_delay -clock [get_clocks clk] -add_delay 1.0 [get_ports hit]
set_clock_uncertainty -setup 0.1 [get_clocks clk]
set_clock_uncertainty -hold 0.1 [get_clocks clk]
