
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 12 2026 22:24:31 IST (May 12 2026 16:54:31 UTC)

// Verification Directory fv/ECC_Cache_System 

module ECC_Cache_System(clk, rst, write_en, read_en, data_in, address,
     codeword_received, display_enable, data_out, hit);
  input clk, rst, write_en, read_en, display_enable;
  input [1:16] data_in;
  input [1:6] address;
  input [1:23] codeword_received;
  output [8:23] data_out;
  output hit;
  wire clk, rst, write_en, read_en, display_enable;
  wire [1:16] data_in;
  wire [1:6] address;
  wire [1:23] codeword_received;
  wire [8:23] data_out;
  wire hit;
  wire [1:23] codeword_reg;
  wire [1:23] cache_codeword;
  wire [1:23] \cache_data_way1[3] ;
  wire [1:23] \cache_data_way0[2] ;
  wire [1:6] \cache_addr_way0[2] ;
  wire [1:23] \cache_data_way0[4] ;
  wire [1:23] \cache_data_way1[2] ;
  wire [1:23] \cache_data_way1[4] ;
  wire [1:6] \cache_addr_way0[4] ;
  wire [1:6] \cache_addr_way1[2] ;
  wire [1:6] \cache_addr_way1[3] ;
  wire [1:6] \cache_addr_way1[4] ;
  wire [1:6] \cache_addr_way0[3] ;
  wire [1:23] \cache_data_way0[3] ;
  wire [1:23] \cache_data_way1[1] ;
  wire [1:6] \cache_addr_way1[1] ;
  wire [1:6] \cache_addr_way0[1] ;
  wire [1:23] \cache_data_way0[1] ;
  wire cache_hit_int, \cache_lru[1] , \cache_lru[2] , \cache_lru[3] ,
       \cache_lru[4] , \cache_valid_way0[1] , \cache_valid_way1[1] ,
       n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_66;
  wire n_67, n_68, n_70, n_71, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_138, n_139, n_140, n_141;
  wire n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189;
  wire n_190, n_191, n_192, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_234, n_235, n_236, n_237, n_238, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_251, n_252, n_253, n_254, n_255, n_256;
  wire n_257, n_258, n_259, n_260, n_261, n_262, n_263, n_264;
  wire n_265, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_282, n_283, n_284, n_285, n_286, n_287, n_288, n_289;
  wire n_290, n_291, n_292, n_293, n_294, n_295, n_296, n_297;
  wire n_298, n_299, n_300, n_301, n_304, n_305, n_306, n_307;
  wire n_308, n_309, n_310, n_311, n_312, n_313, n_314, n_315;
  wire n_317, n_319, n_320, n_321, n_322, n_323, n_324, n_325;
  wire n_326, n_327, n_328, n_329, n_330, n_331, n_332, n_333;
  wire n_334, n_335, n_336, n_337, n_338, n_339, n_340, n_341;
  wire n_342, n_343, n_344, n_346, n_347, n_348, n_349, n_350;
  wire n_351, n_352, n_353, n_354, n_355, n_356, n_357, n_359;
  wire n_360, n_361, n_362, n_363, n_364, n_365, n_366, n_367;
  wire n_368, n_369, n_370, n_372, n_373, n_374, n_375, n_376;
  wire n_377, n_378, n_379, n_381, n_382, n_383, n_384, n_385;
  wire n_386, n_387, n_388, n_389, n_390, n_391, n_392, n_393;
  wire n_394, n_395, n_396, n_397, n_398, n_399, n_400, n_401;
  wire n_402, n_403, n_404, n_405, n_406, n_407, n_408, n_409;
  wire n_410, n_411, n_412, n_413, n_414, n_415, n_416, n_417;
  wire n_418, n_419, n_420, n_421, n_422, n_423, n_424, n_425;
  wire n_426, n_427, n_428, n_429, n_430, n_431, n_432, n_433;
  wire n_435, n_436, n_437, n_438, n_439, n_440, n_441, n_442;
  wire n_443, n_444, n_445, n_446, n_447, n_448, n_449, n_450;
  wire n_451, n_452, n_453, n_454, n_455, n_456, n_457, n_458;
  wire n_459, n_460, n_461, n_462, n_463, n_464, n_465, n_466;
  wire n_467, n_468, n_469, n_470, n_471, n_473, n_474, n_475;
  wire n_476, n_477, n_479, n_480, n_481, n_482, n_483, n_484;
  wire n_485, n_486, n_487, n_488, n_489, n_490, n_491, n_492;
  wire n_493, n_494, n_495, n_496, n_497, n_498, n_499, n_500;
  wire n_501, n_502, n_503, n_504, n_505, n_506, n_507, n_508;
  wire n_509, n_510, n_511, n_512, n_513, n_514, n_515, n_516;
  wire n_517, n_518, n_519, n_521, n_522, n_525, n_528, n_529;
  wire n_530, n_531, n_532, n_535, n_536, n_539, n_546, n_582;
  wire n_583, n_584, n_585, n_586, n_587, n_588, n_589, n_590;
  wire n_591;
  XOR2X2 g25290__2398(.A (codeword_reg[15]), .B (n_546), .Y
       (data_out[15]));
  OAI22XL g25291__5107(.A0 (n_528), .A1 (n_517), .B0 (n_530), .B1
       (n_539), .Y (n_546));
  XOR2X2 g25295__6260(.A (codeword_reg[13]), .B (n_536), .Y
       (data_out[13]));
  XOR2X2 g25293__4319(.A (codeword_reg[18]), .B (n_531), .Y
       (data_out[18]));
  XOR2X2 g25292__8428(.A (codeword_reg[20]), .B (n_532), .Y
       (data_out[20]));
  XOR2X2 g25294__5526(.A (codeword_reg[11]), .B (n_525), .Y
       (data_out[11]));
  XOR2X2 g25303__6783(.A (codeword_reg[14]), .B (n_522), .Y
       (data_out[14]));
  XOR2X2 g25307__3680(.A (codeword_reg[10]), .B (n_511), .Y
       (data_out[10]));
  OAI21XL g25296__1617(.A0 (n_535), .A1 (n_384), .B0 (n_529), .Y
       (n_539));
  XOR2X2 g25309__2802(.A (codeword_reg[12]), .B (n_518), .Y
       (data_out[12]));
  XOR2X2 g25301__1705(.A (codeword_reg[17]), .B (n_513), .Y
       (data_out[17]));
  OAI22XL g25304__5122(.A0 (n_470), .A1 (n_514), .B0 (n_535), .B1
       (n_414), .Y (n_536));
  XOR2X2 g25300__8246(.A (codeword_reg[19]), .B (n_519), .Y
       (data_out[19]));
  XOR2X2 g25308__7098(.A (codeword_reg[16]), .B (n_516), .Y
       (data_out[16]));
  OAI33X1 g25297__6131(.A0 (n_504), .A1 (n_500), .A2 (n_438), .B0
       (n_502), .B1 (n_339), .B2 (n_509), .Y (n_532));
  OAI22XL g25298__1881(.A0 (n_515), .A1 (n_510), .B0 (n_530), .B1
       (n_512), .Y (n_531));
  OAI33X1 g25302__5115(.A0 (n_528), .A1 (n_362), .A2 (n_482), .B0
       (n_521), .B1 (n_419), .B2 (n_485), .Y (n_529));
  XOR2X2 g25323__7482(.A (codeword_reg[9]), .B (n_505), .Y
       (data_out[9]));
  XOR2X2 g25299__4733(.A (codeword_reg[8]), .B (n_494), .Y
       (data_out[8]));
  OAI31X1 g25305__6161(.A0 (n_535), .A1 (n_465), .A2 (n_346), .B0
       (n_507), .Y (n_525));
  XOR2X2 g25313__9315(.A (codeword_reg[23]), .B (n_491), .Y
       (data_out[23]));
  XOR2X2 g25306__9945(.A (codeword_reg[22]), .B (n_501), .Y
       (data_out[22]));
  OAI31X1 g25318__2883(.A0 (n_521), .A1 (n_418), .A2 (n_373), .B0
       (n_508), .Y (n_522));
  XOR2X2 g25315__2346(.A (codeword_reg[21]), .B (n_479), .Y
       (data_out[21]));
  OAI31X1 g25311__1666(.A0 (n_409), .A1 (n_363), .A2 (n_375), .B0
       (n_503), .Y (n_519));
  OAI22XL g25320__7410(.A0 (n_521), .A1 (n_517), .B0 (n_498), .B1
       (n_487), .Y (n_518));
  OAI22XL g25325__6417(.A0 (n_388), .A1 (n_483), .B0 (n_515), .B1
       (n_451), .Y (n_516));
  AOI21XL g25317__5477(.A0 (n_493), .A1 (n_408), .B0 (n_499), .Y
       (n_514));
  OAI33X1 g25316__2398(.A0 (n_495), .A1 (n_466), .A2 (n_477), .B0
       (n_535), .B1 (n_489), .B2 (n_488), .Y (n_513));
  OAI221X1 g25314__5107(.A0 (n_490), .A1 (n_405), .B0 (n_521), .B1
       (n_365), .C0 (n_497), .Y (n_512));
  OAI222X1 g25319__6260(.A0 (n_323), .A1 (n_510), .B0 (n_528), .B1
       (n_583), .C0 (n_521), .C1 (n_469), .Y (n_511));
  MXI2XL g25321__4319(.A (n_389), .B (n_476), .S0 (n_521), .Y (n_509));
  AOI21XL g25329__8428(.A0 (n_506), .A1 (n_480), .B0 (n_486), .Y
       (n_508));
  AOI222X1 g25310__5526(.A0 (n_528), .A1 (n_468), .B0 (n_506), .B1
       (n_400), .C0 (n_521), .C1 (n_474), .Y (n_507));
  OAI211X1 g25343__6783(.A0 (n_504), .A1 (n_417), .B0 (n_453), .C0
       (n_492), .Y (n_505));
  AOI33X1 g25322__3680(.A0 (n_521), .A1 (n_475), .A2 (n_464), .B0
       (n_502), .B1 (n_432), .B2 (n_424), .Y (n_503));
  OAI33X1 g25324__1617(.A0 (n_535), .A1 (n_500), .A2 (n_435), .B0
       (n_502), .B1 (n_437), .B2 (n_463), .Y (n_501));
  AOI31X1 g25328__2802(.A0 (n_496), .A1 (n_443), .A2 (n_459), .B0
       (n_498), .Y (n_499));
  AOI221X1 g25327__1705(.A0 (n_436), .A1 (n_310), .B0 (n_496), .B1
       (n_452), .C0 (n_495), .Y (n_497));
  OAI211X1 g25312__5122(.A0 (n_493), .A1 (n_473), .B0 (n_347), .C0
       (n_492), .Y (n_494));
  OAI33X1 g25332__8246(.A0 (n_372), .A1 (n_462), .A2 (n_450), .B0
       (n_490), .B1 (n_489), .B2 (n_488), .Y (n_491));
  OAI22XL g25339__7098(.A0 (n_521), .A1 (n_455), .B0 (n_484), .B1
       (n_458), .Y (n_487));
  OAI22XL g25341__6131(.A0 (n_515), .A1 (n_485), .B0 (n_484), .B1
       (n_456), .Y (n_486));
  MXI2XL g25342__1881(.A (n_433), .B (n_457), .S0 (n_481), .Y (n_483));
  OAI22XL g25330__5115(.A0 (n_449), .A1 (n_447), .B0 (n_481), .B1
       (n_480), .Y (n_482));
  OAI33X1 g25331__7482(.A0 (n_394), .A1 (n_397), .A2 (n_442), .B0
       (n_441), .B1 (n_489), .B2 (n_510), .Y (n_479));
  NOR2XL g25326__6161(.A (n_484), .B (n_461), .Y (n_477));
  AND3XL g25333__9315(.A (n_368), .B (n_393), .C (n_475), .Y (n_476));
  OAI21XL g25334__9945(.A0 (n_489), .A1 (n_467), .B0 (n_471), .Y
       (n_474));
  NOR2XL g25337__2883(.A (n_504), .B (n_480), .Y (n_498));
  AOI22X1 g25338__2346(.A0 (n_496), .A1 (n_429), .B0 (n_506), .B1
       (n_425), .Y (n_473));
  NOR2XL g25345__1666(.A (n_521), .B (n_440), .Y (n_470));
  AOI21XL g25369__7410(.A0 (n_454), .A1 (n_391), .B0 (n_444), .Y
       (n_469));
  NOR3BX1 g25348__6417(.AN (n_467), .B (n_407), .C (n_584), .Y (n_468));
  OAI22XL g25336__5477(.A0 (n_490), .A1 (n_378), .B0 (n_521), .B1
       (n_426), .Y (n_466));
  NAND2X1 g25347__2398(.A (n_465), .B (n_445), .Y (n_492));
  OAI2BB1X1 g25349__5107(.A0N (n_460), .A1N (n_404), .B0 (n_481), .Y
       (n_464));
  AOI2BB1X1 g25350__6260(.A0N (n_382), .A1N (n_462), .B0 (n_528), .Y
       (n_463));
  AND4XL g25340__4319(.A (n_460), .B (n_459), .C (n_446), .D (n_402),
       .Y (n_461));
  NAND2X1 g25346__8428(.A (n_481), .B (n_458), .Y (n_471));
  MXI2XL g25351__5526(.A (n_413), .B (n_367), .S0 (n_500), .Y (n_480));
  INVX1 g25352(.A (n_448), .Y (n_457));
  NOR2XL g25354__6783(.A (n_412), .B (n_430), .Y (n_456));
  AOI21XL g25355__3680(.A0 (n_454), .A1 (n_401), .B0 (n_423), .Y
       (n_455));
  INVX1 g25362(.A (n_439), .Y (n_453));
  OAI211X1 g25364__1617(.A0 (n_327), .A1 (n_451), .B0 (n_460), .C0
       (n_399), .Y (n_452));
  OAI222X1 g25368__2802(.A0 (n_521), .A1 (n_431), .B0 (n_454), .B1
       (n_395), .C0 (n_449), .C1 (n_585), .Y (n_450));
  OAI221X1 g25359__1705(.A0 (n_500), .A1 (n_447), .B0 (n_386), .B1
       (n_485), .C0 (n_446), .Y (n_448));
  AOI221X1 g25358__5122(.A0 (n_359), .A1 (n_398), .B0 (n_481), .B1
       (n_369), .C0 (n_521), .Y (n_445));
  OAI22XL g25382__8246(.A0 (n_428), .A1 (n_467), .B0 (n_449), .B1
       (n_427), .Y (n_444));
  OAI221X1 g25360__7098(.A0 (n_465), .A1 (n_459), .B0 (n_500), .B1
       (n_443), .C0 (n_454), .Y (n_475));
  MX2XL g25370__6131(.A (n_441), .B (n_484), .S0 (n_385), .Y (n_442));
  OAI31X1 g25365__1881(.A0 (n_454), .A1 (n_313), .A2 (n_510), .B0
       (n_411), .Y (n_440));
  OAI33X1 g25363__5115(.A0 (n_535), .A1 (n_500), .A2 (n_438), .B0
       (n_528), .B1 (n_449), .B2 (n_415), .Y (n_439));
  AO22XL g25372__7482(.A0 (n_436), .A1 (n_435), .B0 (n_528), .B1
       (n_381), .Y (n_437));
  AOI2BB1X1 g25387__6161(.A0N (n_432), .A1N (n_431), .B0 (n_387), .Y
       (n_433));
  OAI22XL g25383__9315(.A0 (n_500), .A1 (n_459), .B0 (n_335), .B1
       (n_451), .Y (n_430));
  OAI21XL g25395__9945(.A0 (n_428), .A1 (n_431), .B0 (n_427), .Y
       (n_429));
  NOR2XL g25353__2883(.A (n_422), .B (n_379), .Y (n_426));
  OAI31X1 g25357__2346(.A0 (n_319), .A1 (n_424), .A2 (n_352), .B0
       (n_343), .Y (n_425));
  AOI222X1 g25379__1666(.A0 (n_410), .A1 (n_403), .B0 (n_329), .B1
       (n_422), .C0 (n_465), .C1 (n_421), .Y (n_423));
  OAI222X1 g25366__7410(.A0 (n_419), .A1 (n_467), .B0 (n_481), .B1
       (n_416), .C0 (n_406), .C1 (n_438), .Y (n_420));
  MX2XL g25367__6417(.A (n_376), .B (n_374), .S0 (n_454), .Y (n_418));
  AND3XL g25374__5477(.A (n_334), .B (n_355), .C (n_416), .Y (n_417));
  OAI211X1 g25361__2398(.A0 (n_500), .A1 (n_415), .B0 (n_414), .C0
       (n_356), .Y (n_458));
  NAND2X1 g25380__5107(.A (n_326), .B (n_377), .Y (n_413));
  OAI222X1 g25381__6260(.A0 (n_315), .A1 (n_510), .B0 (n_321), .B1
       (n_485), .C0 (n_349), .C1 (n_396), .Y (n_412));
  AOI22X1 g25384__4319(.A0 (n_410), .A1 (n_370), .B0 (n_409), .B1
       (n_408), .Y (n_411));
  OAI222X1 g25385__8428(.A0 (n_366), .A1 (n_510), .B0 (n_406), .B1
       (n_405), .C0 (n_500), .C1 (n_390), .Y (n_407));
  AOI222X1 g25386__5526(.A0 (n_322), .A1 (n_422), .B0 (n_325), .B1
       (n_424), .C0 (n_330), .C1 (n_403), .Y (n_404));
  AOI32XL g25388__6783(.A0 (n_337), .A1 (n_401), .A2 (n_403), .B0
       (n_419), .B1 (n_424), .Y (n_402));
  OAI21XL g25391__3680(.A0 (n_586), .A1 (n_485), .B0 (n_416), .Y
       (n_400));
  OAI211X1 g25378__1617(.A0 (n_410), .A1 (n_398), .B0 (n_500), .C0
       (n_348), .Y (n_399));
  OAI22XL g25356__2802(.A0 (n_314), .A1 (n_396), .B0 (n_465), .B1
       (n_392), .Y (n_397));
  INVX1 g25406(.A (n_394), .Y (n_395));
  OAI2BB1X1 g25371__1705(.A0N (n_383), .A1N (n_392), .B0 (n_493), .Y
       (n_393));
  AOI2BB1X1 g25397__5122(.A0N (n_364), .A1N (n_451), .B0 (n_481), .Y
       (n_462));
  AO21X1 g25392__8246(.A0 (n_390), .A1 (n_424), .B0 (n_405), .Y
       (n_391));
  AOI21XL g25394__7098(.A0 (n_465), .A1 (n_438), .B0 (n_422), .Y
       (n_389));
  MXI2XL g25398__6131(.A (n_528), .B (n_521), .S0 (n_338), .Y (n_388));
  OAI22XL g25400__1881(.A0 (n_308), .A1 (n_396), .B0 (n_465), .B1
       (n_386), .Y (n_387));
  MX2XL g25402__5115(.A (n_384), .B (n_383), .S0 (n_500), .Y (n_385));
  NOR3BX1 g25403__7482(.AN (n_443), .B (n_504), .C (n_500), .Y (n_495));
  AOI2BB1X1 g25373__4733(.A0N (n_306), .A1N (n_344), .B0 (n_454), .Y
       (n_382));
  OAI21XL g25424__6161(.A0 (n_500), .A1 (n_360), .B0 (n_451), .Y
       (n_381));
  OAI211X1 g25376__9945(.A0 (n_409), .A1 (n_378), .B0 (n_336), .C0
       (n_357), .Y (n_379));
  NOR2XL g25412__2883(.A (n_384), .B (n_451), .Y (n_394));
  INVX1 g25407(.A (n_421), .Y (n_427));
  ADDHXL g25390__2346(.A (n_311), .B (n_488), .CO (n_376), .S (n_377));
  OAI221X1 g25396__1666(.A0 (n_465), .A1 (n_354), .B0 (n_587), .B1
       (n_374), .C0 (n_342), .Y (n_375));
  AOI22X1 g25399__7410(.A0 (n_500), .A1 (n_408), .B0 (n_331), .B1
       (n_422), .Y (n_373));
  AO22XL g25401__6417(.A0 (n_521), .A1 (n_431), .B0 (n_493), .B1
       (n_435), .Y (n_372));
  NAND2BX1 g25408__5477(.AN (n_383), .B (n_374), .Y (n_369));
  AO21X1 g25393__2398(.A0 (n_361), .A1 (n_398), .B0 (n_449), .Y
       (n_368));
  NAND2BX1 g25410__5107(.AN (n_438), .B (n_493), .Y (n_517));
  OAI21XL g25420__6260(.A0 (n_366), .A1 (n_488), .B0 (n_340), .Y
       (n_367));
  AOI211XL g25377__4319(.A0 (n_364), .A1 (n_353), .B0 (n_307), .C0
       (n_363), .Y (n_365));
  AOI221X1 g25375__8428(.A0 (n_361), .A1 (n_431), .B0 (n_320), .B1
       (n_363), .C0 (n_301), .Y (n_362));
  OA21X1 g25413__5526(.A0 (n_332), .A1 (n_488), .B0 (n_443), .Y
       (n_415));
  MX2XL g25427__6783(.A (n_333), .B (n_360), .S0 (n_488), .Y (n_447));
  NOR2XL g25416__3680(.A (n_359), .B (n_383), .Y (n_421));
  NAND2BX1 g25415__1617(.AN (n_586), .B (n_424), .Y (n_416));
  OR2X1 g25417__2802(.A (n_357), .B (n_383), .Y (n_459));
  OAI21XL g25418__1705(.A0 (n_408), .A1 (n_350), .B0 (n_422), .Y
       (n_356));
  OAI21XL g25421__5122(.A0 (n_351), .A1 (n_354), .B0 (n_353), .Y
       (n_355));
  OAI2BB1X1 g25423__8246(.A0N (n_500), .A1N (n_410), .B0 (n_485), .Y
       (n_352));
  OAI2BB1X1 g25425__7098(.A0N (n_341), .A1N (n_401), .B0 (n_422), .Y
       (n_446));
  NOR2XL g25411__6131(.A (n_454), .B (n_485), .Y (n_370));
  AOI211XL g25404__1881(.A0 (n_351), .A1 (n_488), .B0 (n_361), .C0
       (n_350), .Y (n_392));
  NAND2X1 g25414__5115(.A (n_349), .B (n_353), .Y (n_460));
  OAI211X1 g25445__7482(.A0 (n_384), .A1 (n_390), .B0 (n_304), .C0
       (n_488), .Y (n_348));
  NAND4X1 g25444__4733(.A (n_454), .B (n_384), .C (n_390), .D (n_488),
       .Y (n_347));
  INVX1 g25429(.A (n_378), .Y (n_346));
  NAND2BX1 g25426__6161(.AN (n_435), .B (n_500), .Y (n_414));
  NAND2X1 g25428__9315(.A (n_454), .B (n_353), .Y (n_467));
  INVX1 g25432(.A (n_424), .Y (n_451));
  MX2XL g25419__9945(.A (n_312), .B (n_343), .S0 (n_431), .Y (n_344));
  AOI22X1 g25422__2883(.A0 (n_341), .A1 (n_431), .B0 (n_441), .B1
       (n_374), .Y (n_342));
  INVX1 g25430(.A (n_363), .Y (n_340));
  NOR2XL g25434__2346(.A (n_364), .B (n_488), .Y (n_378));
  INVX1 g25431(.A (n_485), .Y (n_403));
  NAND2BX1 g25436__1666(.AN (n_349), .B (n_488), .Y (n_443));
  OA21X1 g25452__7410(.A0 (n_328), .A1 (n_361), .B0 (n_436), .Y
       (n_339));
  OAI211X1 g25446__6417(.A0 (n_409), .A1 (n_337), .B0 (n_336), .C0
       (n_431), .Y (n_338));
  INVX1 g25442(.A (n_353), .Y (n_396));
  OR2X1 g25438__5477(.A (n_335), .B (n_488), .Y (n_438));
  INVX1 g25443(.A (n_422), .Y (n_510));
  OR2X1 g25449__2398(.A (n_337), .B (n_488), .Y (n_383));
  AND2X1 g25440__5107(.A (n_465), .B (n_488), .Y (n_424));
  NAND2BX1 g25433__6260(.AN (n_343), .B (n_431), .Y (n_334));
  NAND2X1 g25435__4319(.A (n_351), .B (n_431), .Y (n_398));
  NOR2XL g25437__8428(.A (n_408), .B (n_431), .Y (n_363));
  NAND2X1 g25439__5526(.A (n_500), .B (n_431), .Y (n_485));
  NOR2XL g25461__6783(.A (n_360), .B (n_361), .Y (n_333));
  AND2X1 g25447__3680(.A (n_408), .B (n_431), .Y (n_405));
  NAND2X1 g25448__1617(.A (n_432), .B (n_431), .Y (n_435));
  AND2X1 g25450__2802(.A (n_465), .B (n_431), .Y (n_353));
  NOR2X1 g25451__1705(.A (n_465), .B (n_431), .Y (n_422));
  NOR2XL g25457__5122(.A (n_331), .B (n_350), .Y (n_332));
  INVX1 g25453(.A (n_431), .Y (n_488));
  AND2X1 g25463__7098(.A (n_428), .B (n_357), .Y (n_386));
  NOR2XL g25456__6131(.A (n_410), .B (n_328), .Y (n_329));
  NOR2XL g25455__1881(.A (n_326), .B (n_328), .Y (n_327));
  NAND2BX1 g25460__5115(.AN (n_328), .B (n_324), .Y (n_325));
  NOR2XL g25459__7482(.A (n_328), .B (n_317), .Y (n_366));
  XNOR2X1 g25454__4733(.A (codeword_reg[23]), .B (n_309), .Y (n_431));
  NAND2BX1 g25462__6161(.AN (n_364), .B (n_506), .Y (n_323));
  INVX1 g25476(.A (n_432), .Y (n_322));
  INVX1 g25477(.A (n_350), .Y (n_335));
  NAND2BX1 g25464__9315(.AN (n_343), .B (n_502), .Y (n_515));
  NOR2BX1 g25465__9945(.AN (n_364), .B (n_408), .Y (n_419));
  INVX1 g25467(.A (n_321), .Y (n_361));
  NAND2BX1 g25468__2883(.AN (n_410), .B (n_319), .Y (n_320));
  NAND2X1 g25471__2346(.A (n_337), .B (n_324), .Y (n_330));
  AND2X1 g25473__1666(.A (n_401), .B (n_324), .Y (n_357));
  NAND2X1 g25475__7410(.A (n_384), .B (n_324), .Y (n_321));
  NOR2XL g25482__6417(.A (n_337), .B (n_324), .Y (n_432));
  NOR2XL g25484__5477(.A (n_384), .B (n_324), .Y (n_350));
  AND2X1 g25470__2398(.A (n_428), .B (n_401), .Y (n_315));
  AND2X1 g25469__5107(.A (n_319), .B (n_313), .Y (n_314));
  OAI21XL g25479__6260(.A0 (n_384), .A1 (n_311), .B0 (n_401), .Y
       (n_312));
  NOR2XL g25472__4319(.A (n_337), .B (n_390), .Y (n_317));
  AND2X1 g25474__8428(.A (n_337), .B (n_310), .Y (n_328));
  NAND2X1 g25481__5526(.A (n_337), .B (n_390), .Y (n_349));
  NAND2BX1 g25483__6783(.AN (n_401), .B (n_337), .Y (n_343));
  OR2X1 g25485__3680(.A (n_337), .B (n_310), .Y (n_489));
  OR2X1 g25486__1617(.A (n_384), .B (n_310), .Y (n_364));
  NOR2X1 g25487__2802(.A (n_337), .B (n_401), .Y (n_408));
  XOR2X1 g25480__1705(.A (codeword_reg[22]), .B (n_305), .Y (n_309));
  INVX1 g25488(.A (n_390), .Y (n_359));
  INVX1 g25492(.A (n_310), .Y (n_308));
  AND2X1 g25495__5122(.A (n_384), .B (n_311), .Y (n_410));
  OR2X1 g25496__8246(.A (n_351), .B (n_311), .Y (n_324));
  NAND2X1 g25489__7098(.A (n_384), .B (n_374), .Y (n_313));
  AND2X1 g25490__6131(.A (n_351), .B (n_374), .Y (n_390));
  OR2X1 g25491__1881(.A (n_319), .B (n_374), .Y (n_401));
  NOR2XL g25493__5115(.A (n_384), .B (n_374), .Y (n_354));
  INVX1 g25497(.A (n_307), .Y (n_336));
  OR2X1 g25494__7482(.A (n_351), .B (n_374), .Y (n_310));
  OAI21XL g25499__4733(.A0 (n_406), .A1 (n_384), .B0 (n_449), .Y
       (n_307));
  INVX1 g25506(.A (n_360), .Y (n_341));
  INVX1 g25500(.A (n_374), .Y (n_311));
  MXI2XL g25498__6161(.A (n_465), .B (n_500), .S0 (n_337), .Y (n_306));
  XOR2X1 g25501__9315(.A (codeword_reg[20]), .B (n_300), .Y (n_305));
  XOR2X1 g25502__9945(.A (codeword_reg[23]), .B (n_299), .Y (n_374));
  INVX1 g25505(.A (n_331), .Y (n_304));
  NOR2XL g25509__2346(.A (n_351), .B (n_384), .Y (n_360));
  NOR2XL g25503__1666(.A (n_351), .B (n_337), .Y (n_326));
  NAND2X1 g25504__7410(.A (n_351), .B (n_337), .Y (n_428));
  NOR2XL g25507__6417(.A (n_441), .B (n_337), .Y (n_530));
  NOR2XL g25508__5477(.A (n_319), .B (n_337), .Y (n_331));
  NAND2X1 g25511__2398(.A (n_521), .B (n_409), .Y (n_490));
  INVX1 g25512(.A (n_337), .Y (n_384));
  INVX1 g25516(.A (n_493), .Y (n_301));
  NAND2X1 g25519__5107(.A (n_481), .B (n_465), .Y (n_449));
  XOR2X1 g25515__6260(.A (codeword_reg[23]), .B (n_296), .Y (n_337));
  XOR2X1 g25513__4319(.A (codeword_reg[17]), .B (n_298), .Y (n_300));
  XOR2X1 g25514__8428(.A (codeword_reg[21]), .B (n_297), .Y (n_299));
  INVX1 g25520(.A (n_409), .Y (n_406));
  NOR2XL g25521__5526(.A (n_521), .B (n_465), .Y (n_436));
  AND2X1 g25518__6783(.A (n_481), .B (n_500), .Y (n_493));
  AND2X1 g25522__3680(.A (n_454), .B (n_500), .Y (n_409));
  INVX1 g25523(.A (n_500), .Y (n_465));
  XOR2X1 g25524__1617(.A (codeword_reg[15]), .B (n_294), .Y (n_298));
  XOR2X2 g25525__2802(.A (codeword_reg[22]), .B (n_293), .Y (n_500));
  XOR2X1 g25526__1705(.A (codeword_reg[18]), .B (n_295), .Y (n_297));
  XOR2X1 g25527__5122(.A (codeword_reg[22]), .B (n_292), .Y (n_296));
  INVX1 g25532(.A (n_484), .Y (n_496));
  XOR2X1 g25530__8246(.A (codeword_reg[17]), .B (n_289), .Y (n_295));
  XOR2X1 g25529__7098(.A (codeword_reg[14]), .B (n_290), .Y (n_294));
  XOR2X1 g25528__6131(.A (codeword_reg[20]), .B (n_291), .Y (n_293));
  XOR2X1 g25531__1881(.A (codeword_reg[21]), .B (n_288), .Y (n_292));
  INVX1 g25536(.A (n_535), .Y (n_502));
  NAND2X1 g25537__5115(.A (n_481), .B (n_528), .Y (n_441));
  INVX1 g25533(.A (n_506), .Y (n_504));
  OR2X1 g25534__7482(.A (n_454), .B (n_528), .Y (n_484));
  AND2X1 g25535__4733(.A (n_454), .B (n_521), .Y (n_506));
  OR2X1 g25538__6161(.A (n_481), .B (n_521), .Y (n_535));
  INVX1 g25539(.A (n_351), .Y (n_319));
  INVX1 g25543(.A (n_521), .Y (n_528));
  XOR2X1 g25540__9315(.A (codeword_reg[19]), .B (n_285), .Y (n_291));
  XOR2X1 g25541__9945(.A (codeword_reg[13]), .B (n_283), .Y (n_290));
  XOR2X1 g25542__2883(.A (codeword_reg[18]), .B (n_286), .Y (n_351));
  XOR2X1 g25544__2346(.A (codeword_reg[16]), .B (n_282), .Y (n_289));
  XOR2X1 g25545__1666(.A (codeword_reg[19]), .B (n_287), .Y (n_288));
  XNOR2X4 g25546__7410(.A (codeword_reg[23]), .B (n_284), .Y (n_521));
  INVX1 g25550(.A (n_454), .Y (n_481));
  XOR2X1 g25547__6417(.A (codeword_reg[17]), .B (n_281), .Y (n_287));
  XOR2X1 g25548__5477(.A (codeword_reg[16]), .B (n_280), .Y (n_286));
  XOR2X1 g25549__2398(.A (codeword_reg[17]), .B (n_279), .Y (n_285));
  XOR2X1 g25553__5107(.A (codeword_reg[20]), .B (n_276), .Y (n_284));
  XOR2X1 g25552__6260(.A (codeword_reg[12]), .B (n_277), .Y (n_283));
  XOR2X1 g25551__4319(.A (codeword_reg[14]), .B (n_278), .Y (n_282));
  XOR2X1 g25554__8428(.A (codeword_reg[21]), .B (n_275), .Y (n_454));
  XOR2X1 g25555__5526(.A (codeword_reg[13]), .B (n_273), .Y (n_281));
  XOR2X1 g25556__6783(.A (codeword_reg[14]), .B (n_269), .Y (n_280));
  XOR2X1 g25557__3680(.A (codeword_reg[16]), .B (n_270), .Y (n_279));
  XOR2X1 g25560__1617(.A (codeword_reg[11]), .B (n_271), .Y (n_278));
  XOR2X1 g25559__2802(.A (codeword_reg[11]), .B (n_268), .Y (n_277));
  XOR2X1 g25558__1705(.A (codeword_reg[15]), .B (n_274), .Y (n_276));
  XOR2X1 g25561__5122(.A (codeword_reg[15]), .B (n_267), .Y (n_275));
  XNOR2X1 g25585__8246(.A (codeword_reg[7]), .B (codeword_reg[10]), .Y
       (n_274));
  XNOR2X1 g25586__7098(.A (codeword_reg[6]), .B (codeword_reg[8]), .Y
       (n_273));
  DFFRHQX2 \cache_lru_reg[3] (.RN (n_272), .CK (clk), .D (n_589), .Q
       (\cache_lru[3] ));
  DFFRHQX2 \cache_lru_reg[4] (.RN (n_272), .CK (clk), .D (n_265), .Q
       (\cache_lru[4] ));
  XNOR2X1 g25589__6131(.A (codeword_reg[5]), .B (codeword_reg[10]), .Y
       (n_271));
  XNOR2X1 g25588__1881(.A (codeword_reg[4]), .B (codeword_reg[9]), .Y
       (n_270));
  XOR2X1 g25587__5115(.A (codeword_reg[2]), .B (codeword_reg[8]), .Y
       (n_269));
  XNOR2X1 g25590__7482(.A (codeword_reg[1]), .B (codeword_reg[9]), .Y
       (n_268));
  XNOR2X1 g25591__4733(.A (codeword_reg[3]), .B (codeword_reg[12]), .Y
       (n_267));
  DFFRHQX2 \cache_codeword_out_reg[2] (.RN (n_272), .CK (clk), .D
       (n_264), .Q (cache_codeword[2]));
  DFFRHQX2 \cache_codeword_out_reg[3] (.RN (n_272), .CK (clk), .D
       (n_254), .Q (cache_codeword[3]));
  DFFRHQX2 \cache_codeword_out_reg[5] (.RN (n_272), .CK (clk), .D
       (n_255), .Q (cache_codeword[5]));
  DFFRHQX2 \cache_codeword_out_reg[6] (.RN (n_272), .CK (clk), .D
       (n_256), .Q (cache_codeword[6]));
  DFFRHQX2 \cache_codeword_out_reg[8] (.RN (n_272), .CK (clk), .D
       (n_253), .Q (cache_codeword[8]));
  DFFRHQX2 \cache_codeword_out_reg[10] (.RN (n_272), .CK (clk), .D
       (n_258), .Q (cache_codeword[10]));
  DFFRHQX2 \cache_codeword_out_reg[7] (.RN (n_272), .CK (clk), .D
       (n_257), .Q (cache_codeword[7]));
  DFFRHQX2 \cache_codeword_out_reg[19] (.RN (n_272), .CK (clk), .D
       (n_261), .Q (cache_codeword[19]));
  DFFRHQX2 \cache_codeword_out_reg[20] (.RN (n_272), .CK (clk), .D
       (n_259), .Q (cache_codeword[20]));
  DFFRHQX2 \cache_codeword_out_reg[21] (.RN (n_272), .CK (clk), .D
       (n_262), .Q (cache_codeword[21]));
  DFFRHQX2 \cache_codeword_out_reg[23] (.RN (n_272), .CK (clk), .D
       (n_263), .Q (cache_codeword[23]));
  DFFRHQX2 \cache_lru_reg[1] (.RN (n_272), .CK (clk), .D (n_251), .Q
       (\cache_lru[1] ));
  DFFRHQX2 \cache_codeword_out_reg[16] (.RN (n_272), .CK (clk), .D
       (n_260), .Q (cache_codeword[16]));
  OAI21XL g25742__9315(.A0 (n_4), .A1 (n_250), .B0 (n_249), .Y (n_265));
  DFFRHQX2 \cache_lru_reg[2] (.RN (n_272), .CK (clk), .D (n_239), .Q
       (\cache_lru[2] ));
  NAND4BX1 g25615__9945(.AN (n_219), .B (n_122), .C (n_176), .D
       (n_158), .Y (n_264));
  NAND4BX1 g25613__2883(.AN (n_207), .B (n_105), .C (n_146), .D
       (n_147), .Y (n_263));
  NAND4BX1 g25611__2346(.AN (n_216), .B (n_103), .C (n_149), .D
       (n_150), .Y (n_262));
  NAND4BX1 g25609__1666(.AN (n_208), .B (n_108), .C (n_156), .D
       (n_157), .Y (n_261));
  NAND4BX1 g25606__7410(.AN (n_204), .B (n_107), .C (n_164), .D (n_81),
       .Y (n_260));
  NAND4BX1 g25604__6417(.AN (n_221), .B (n_116), .C (n_151), .D
       (n_153), .Y (n_259));
  NAND4BX1 g25600__5477(.AN (n_218), .B (n_104), .C (n_177), .D
       (n_152), .Y (n_258));
  NAND4BX1 g25597__2398(.AN (n_206), .B (n_120), .C (n_172), .D
       (n_161), .Y (n_257));
  NAND4BX1 g25596__5107(.AN (n_211), .B (n_129), .C (n_144), .D
       (n_140), .Y (n_256));
  NAND4BX1 g25595__6260(.AN (n_205), .B (n_106), .C (n_155), .D
       (n_138), .Y (n_255));
  NAND4BX1 g25593__4319(.AN (n_212), .B (n_112), .C (n_139), .D
       (n_187), .Y (n_254));
  NAND4BX1 g25592__8428(.AN (n_210), .B (n_121), .C (n_141), .D
       (n_143), .Y (n_253));
  DFFRHQX2 \cache_codeword_out_reg[13] (.RN (n_272), .CK (clk), .D
       (n_222), .Q (cache_codeword[13]));
  DFFRHQX2 \cache_codeword_out_reg[15] (.RN (n_272), .CK (clk), .D
       (n_229), .Q (cache_codeword[15]));
  DFFRHQX2 \cache_codeword_out_reg[1] (.RN (n_272), .CK (clk), .D
       (n_224), .Q (cache_codeword[1]));
  DFFRHQX2 \cache_codeword_out_reg[22] (.RN (n_272), .CK (clk), .D
       (n_225), .Q (cache_codeword[22]));
  DFFRHQX2 \cache_codeword_out_reg[14] (.RN (n_272), .CK (clk), .D
       (n_226), .Q (cache_codeword[14]));
  DFFRHQX2 \cache_codeword_out_reg[11] (.RN (n_272), .CK (clk), .D
       (n_231), .Q (cache_codeword[11]));
  DFFRHQX2 \cache_codeword_out_reg[12] (.RN (n_272), .CK (clk), .D
       (n_230), .Q (cache_codeword[12]));
  DFFRHQX2 \cache_codeword_out_reg[4] (.RN (n_272), .CK (clk), .D
       (n_234), .Q (cache_codeword[4]));
  DFFRHQX2 \cache_codeword_out_reg[9] (.RN (n_272), .CK (clk), .D
       (n_227), .Q (cache_codeword[9]));
  DFFRHQX2 \cache_codeword_out_reg[18] (.RN (n_272), .CK (clk), .D
       (n_232), .Q (cache_codeword[18]));
  DFFRHQX2 \cache_codeword_out_reg[17] (.RN (n_272), .CK (clk), .D
       (n_228), .Q (cache_codeword[17]));
  SDFFRHQX1 \codeword_reg_reg[4] (.RN (n_272), .CK (clk), .D
       (cache_codeword[4]), .SE (n_252), .SI (codeword_received[4]), .Q
       (codeword_reg[4]));
  SDFFRHQX1 \codeword_reg_reg[7] (.RN (n_272), .CK (clk), .D
       (cache_codeword[7]), .SE (n_252), .SI (codeword_received[7]), .Q
       (codeword_reg[7]));
  SDFFRHQX1 \codeword_reg_reg[6] (.RN (n_272), .CK (clk), .D
       (cache_codeword[6]), .SE (n_252), .SI (codeword_received[6]), .Q
       (codeword_reg[6]));
  SDFFRHQX1 \codeword_reg_reg[2] (.RN (n_272), .CK (clk), .D
       (cache_codeword[2]), .SE (n_252), .SI (codeword_received[2]), .Q
       (codeword_reg[2]));
  OAI21XL g25744__5526(.A0 (n_14), .A1 (n_250), .B0 (n_235), .Y
       (n_251));
  SDFFRHQX1 \codeword_reg_reg[1] (.RN (n_272), .CK (clk), .D
       (cache_codeword[1]), .SE (n_252), .SI (codeword_received[1]), .Q
       (codeword_reg[1]));
  SDFFRHQX1 \codeword_reg_reg[5] (.RN (n_272), .CK (clk), .D
       (cache_codeword[5]), .SE (n_252), .SI (codeword_received[5]), .Q
       (codeword_reg[5]));
  SDFFRHQX1 \codeword_reg_reg[3] (.RN (n_272), .CK (clk), .D
       (cache_codeword[3]), .SE (n_252), .SI (codeword_received[3]), .Q
       (codeword_reg[3]));
  SDFFRHQX1 \codeword_reg_reg[18] (.RN (n_272), .CK (clk), .D
       (cache_codeword[18]), .SE (n_252), .SI (codeword_received[18]),
       .Q (codeword_reg[18]));
  SDFFRHQX1 \codeword_reg_reg[19] (.RN (n_272), .CK (clk), .D
       (cache_codeword[19]), .SE (n_252), .SI (codeword_received[19]),
       .Q (codeword_reg[19]));
  SDFFRHQX1 \codeword_reg_reg[13] (.RN (n_272), .CK (clk), .D
       (cache_codeword[13]), .SE (n_252), .SI (codeword_received[13]),
       .Q (codeword_reg[13]));
  SDFFRHQX1 \codeword_reg_reg[10] (.RN (n_272), .CK (clk), .D
       (cache_codeword[10]), .SE (n_252), .SI (codeword_received[10]),
       .Q (codeword_reg[10]));
  SDFFRHQX1 \codeword_reg_reg[12] (.RN (n_272), .CK (clk), .D
       (cache_codeword[12]), .SE (n_252), .SI (codeword_received[12]),
       .Q (codeword_reg[12]));
  SDFFRHQX1 \codeword_reg_reg[11] (.RN (n_272), .CK (clk), .D
       (cache_codeword[11]), .SE (n_252), .SI (codeword_received[11]),
       .Q (codeword_reg[11]));
  SDFFRHQX1 \codeword_reg_reg[8] (.RN (n_272), .CK (clk), .D
       (cache_codeword[8]), .SE (n_252), .SI (codeword_received[8]), .Q
       (codeword_reg[8]));
  SDFFRHQX1 \codeword_reg_reg[9] (.RN (n_272), .CK (clk), .D
       (cache_codeword[9]), .SE (n_252), .SI (codeword_received[9]), .Q
       (codeword_reg[9]));
  SDFFRHQX1 \codeword_reg_reg[20] (.RN (n_272), .CK (clk), .D
       (cache_codeword[20]), .SE (n_252), .SI (codeword_received[20]),
       .Q (codeword_reg[20]));
  SDFFRHQX1 \codeword_reg_reg[22] (.RN (n_272), .CK (clk), .D
       (cache_codeword[22]), .SE (n_252), .SI (codeword_received[22]),
       .Q (codeword_reg[22]));
  SDFFRHQX1 \codeword_reg_reg[15] (.RN (n_272), .CK (clk), .D
       (cache_codeword[15]), .SE (n_252), .SI (codeword_received[15]),
       .Q (codeword_reg[15]));
  SDFFRHQX1 \codeword_reg_reg[21] (.RN (n_272), .CK (clk), .D
       (cache_codeword[21]), .SE (n_252), .SI (codeword_received[21]),
       .Q (codeword_reg[21]));
  SDFFRHQX1 \codeword_reg_reg[14] (.RN (n_272), .CK (clk), .D
       (cache_codeword[14]), .SE (n_252), .SI (codeword_received[14]),
       .Q (codeword_reg[14]));
  SDFFRHQX1 \codeword_reg_reg[16] (.RN (n_272), .CK (clk), .D
       (cache_codeword[16]), .SE (n_252), .SI (codeword_received[16]),
       .Q (codeword_reg[16]));
  SDFFRHQX1 \codeword_reg_reg[17] (.RN (n_272), .CK (clk), .D
       (cache_codeword[17]), .SE (n_252), .SI (codeword_received[17]),
       .Q (codeword_reg[17]));
  SDFFRHQX1 \codeword_reg_reg[23] (.RN (n_272), .CK (clk), .D
       (cache_codeword[23]), .SE (n_252), .SI (codeword_received[23]),
       .Q (codeword_reg[23]));
  OAI2BB1X1 g25869__6783(.A0N (address[6]), .A1N (n_203), .B0
       (\cache_lru[4] ), .Y (n_249));
  SDFFRHQX1 \cache_data_way1_reg[3][2] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [2]), .SE (n_247), .SI (n_244), .Q
       (\cache_data_way1[3] [2]));
  SDFFRHQX1 \cache_data_way0_reg[2][3] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [3]), .SE (n_248), .SI (n_237), .Q
       (\cache_data_way0[2] [3]));
  SDFFRHQX1 \cache_data_way0_reg[2][16] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [16]), .SE (n_248), .SI (data_in[9]), .Q
       (\cache_data_way0[2] [16]));
  SDFFRHQX1 \cache_addr_way0_reg[2][3] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way0[2] [3]), .SE (n_248), .SI (address[3]), .Q
       (\cache_addr_way0[2] [3]));
  SDFFRHQX1 \cache_data_way1_reg[3][11] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [11]), .SE (n_247), .SI (data_in[4]), .Q
       (\cache_data_way1[3] [11]));
  SDFFRHQX1 \cache_data_way0_reg[4][20] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [20]), .SE (n_246), .SI (data_in[13]), .Q
       (\cache_data_way0[4] [20]));
  SDFFRHQX1 \cache_data_way0_reg[4][22] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [22]), .SE (n_246), .SI (data_in[15]), .Q
       (\cache_data_way0[4] [22]));
  SDFFRHQX1 \cache_data_way1_reg[3][9] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [9]), .SE (n_247), .SI (data_in[2]), .Q
       (\cache_data_way1[3] [9]));
  SDFFRHQX1 \cache_data_way1_reg[2][1] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [1]), .SE (n_245), .SI (n_238), .Q
       (\cache_data_way1[2] [1]));
  SDFFRHQX1 \cache_data_way1_reg[2][2] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [2]), .SE (n_245), .SI (n_244), .Q
       (\cache_data_way1[2] [2]));
  SDFFRHQX1 \cache_data_way1_reg[2][4] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [4]), .SE (n_245), .SI (n_242), .Q
       (\cache_data_way1[2] [4]));
  SDFFRHQX1 \cache_data_way1_reg[2][5] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [5]), .SE (n_245), .SI (n_236), .Q
       (\cache_data_way1[2] [5]));
  SDFFRHQX1 \cache_data_way1_reg[2][6] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [6]), .SE (n_245), .SI (n_243), .Q
       (\cache_data_way1[2] [6]));
  SDFFRHQX1 \cache_data_way1_reg[2][8] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [8]), .SE (n_245), .SI (data_in[1]), .Q
       (\cache_data_way1[2] [8]));
  SDFFRHQX1 \cache_data_way1_reg[2][10] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [10]), .SE (n_245), .SI (data_in[3]), .Q
       (\cache_data_way1[2] [10]));
  SDFFRHQX1 \cache_data_way0_reg[4][6] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [6]), .SE (n_246), .SI (n_243), .Q
       (\cache_data_way0[4] [6]));
  SDFFRHQX1 \cache_data_way1_reg[2][12] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [12]), .SE (n_245), .SI (data_in[5]), .Q
       (\cache_data_way1[2] [12]));
  SDFFRHQX1 \cache_data_way1_reg[2][14] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [14]), .SE (n_245), .SI (data_in[7]), .Q
       (\cache_data_way1[2] [14]));
  SDFFRHQX1 \cache_data_way1_reg[2][16] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [16]), .SE (n_245), .SI (data_in[9]), .Q
       (\cache_data_way1[2] [16]));
  SDFFRHQX1 \cache_data_way1_reg[2][18] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [18]), .SE (n_245), .SI (data_in[11]), .Q
       (\cache_data_way1[2] [18]));
  SDFFRHQX1 \cache_data_way1_reg[2][19] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [19]), .SE (n_245), .SI (data_in[12]), .Q
       (\cache_data_way1[2] [19]));
  SDFFRHQX1 \cache_data_way0_reg[4][19] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [19]), .SE (n_246), .SI (data_in[12]), .Q
       (\cache_data_way0[4] [19]));
  SDFFRHQX1 \cache_data_way1_reg[2][23] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [23]), .SE (n_245), .SI (data_in[16]), .Q
       (\cache_data_way1[2] [23]));
  SDFFRHQX1 \cache_data_way1_reg[3][23] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [23]), .SE (n_247), .SI (data_in[16]), .Q
       (\cache_data_way1[3] [23]));
  SDFFRHQX1 \cache_data_way1_reg[3][4] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [4]), .SE (n_247), .SI (n_242), .Q
       (\cache_data_way1[3] [4]));
  SDFFRHQX1 \cache_data_way1_reg[3][6] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [6]), .SE (n_247), .SI (n_243), .Q
       (\cache_data_way1[3] [6]));
  SDFFRHQX1 \cache_data_way1_reg[3][8] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [8]), .SE (n_247), .SI (data_in[1]), .Q
       (\cache_data_way1[3] [8]));
  SDFFRHQX1 \cache_data_way1_reg[3][10] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [10]), .SE (n_247), .SI (data_in[3]), .Q
       (\cache_data_way1[3] [10]));
  SDFFRHQX1 \cache_data_way1_reg[3][12] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [12]), .SE (n_247), .SI (data_in[5]), .Q
       (\cache_data_way1[3] [12]));
  SDFFRHQX1 \cache_data_way1_reg[3][13] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [13]), .SE (n_247), .SI (data_in[6]), .Q
       (\cache_data_way1[3] [13]));
  SDFFRHQX1 \cache_data_way1_reg[3][14] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [14]), .SE (n_247), .SI (data_in[7]), .Q
       (\cache_data_way1[3] [14]));
  SDFFRHQX1 \cache_data_way1_reg[3][17] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [17]), .SE (n_247), .SI (data_in[10]), .Q
       (\cache_data_way1[3] [17]));
  SDFFRHQX1 \cache_data_way1_reg[3][19] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [19]), .SE (n_247), .SI (data_in[12]), .Q
       (\cache_data_way1[3] [19]));
  SDFFRHQX1 \cache_data_way1_reg[3][21] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [21]), .SE (n_247), .SI (data_in[14]), .Q
       (\cache_data_way1[3] [21]));
  SDFFRHQX1 \cache_data_way1_reg[4][16] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [16]), .SE (n_241), .SI (data_in[9]), .Q
       (\cache_data_way1[4] [16]));
  SDFFRHQX1 \cache_data_way1_reg[4][2] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [2]), .SE (n_241), .SI (n_244), .Q
       (\cache_data_way1[4] [2]));
  SDFFRHQX1 \cache_data_way1_reg[4][4] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [4]), .SE (n_241), .SI (n_242), .Q
       (\cache_data_way1[4] [4]));
  SDFFRHQX1 \cache_data_way1_reg[4][6] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [6]), .SE (n_241), .SI (n_243), .Q
       (\cache_data_way1[4] [6]));
  SDFFRHQX1 \cache_data_way1_reg[4][9] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [9]), .SE (n_241), .SI (data_in[2]), .Q
       (\cache_data_way1[4] [9]));
  SDFFRHQX1 \cache_data_way1_reg[4][11] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [11]), .SE (n_241), .SI (data_in[4]), .Q
       (\cache_data_way1[4] [11]));
  SDFFRHQX1 \cache_data_way1_reg[4][13] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [13]), .SE (n_241), .SI (data_in[6]), .Q
       (\cache_data_way1[4] [13]));
  SDFFRHQX1 \cache_data_way1_reg[4][15] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [15]), .SE (n_241), .SI (data_in[8]), .Q
       (\cache_data_way1[4] [15]));
  SDFFRHQX1 \cache_data_way1_reg[4][17] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [17]), .SE (n_241), .SI (data_in[10]), .Q
       (\cache_data_way1[4] [17]));
  SDFFRHQX1 \cache_data_way1_reg[4][19] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [19]), .SE (n_241), .SI (data_in[12]), .Q
       (\cache_data_way1[4] [19]));
  SDFFRHQX1 \cache_data_way1_reg[4][20] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [20]), .SE (n_241), .SI (data_in[13]), .Q
       (\cache_data_way1[4] [20]));
  SDFFRHQX1 \cache_data_way1_reg[4][21] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [21]), .SE (n_241), .SI (data_in[14]), .Q
       (\cache_data_way1[4] [21]));
  SDFFRHQX1 \cache_data_way1_reg[2][7] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [7]), .SE (n_245), .SI (n_240), .Q
       (\cache_data_way1[2] [7]));
  SDFFRHQX1 \cache_data_way1_reg[4][23] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [23]), .SE (n_241), .SI (data_in[16]), .Q
       (\cache_data_way1[4] [23]));
  SDFFRHQX1 \cache_addr_way0_reg[2][2] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way0[2] [2]), .SE (n_248), .SI (address[2]), .Q
       (\cache_addr_way0[2] [2]));
  SDFFRHQX1 \cache_addr_way0_reg[4][1] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way0[4] [1]), .SE (n_246), .SI (address[1]), .Q
       (\cache_addr_way0[4] [1]));
  SDFFRHQX1 \cache_addr_way0_reg[4][3] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way0[4] [3]), .SE (n_246), .SI (address[3]), .Q
       (\cache_addr_way0[4] [3]));
  SDFFRHQX1 \cache_addr_way0_reg[4][5] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way0[4] [5]), .SE (n_246), .SI (address[5]), .Q
       (\cache_addr_way0[4] [5]));
  SDFFRHQX1 \cache_data_way0_reg[2][2] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [2]), .SE (n_248), .SI (n_244), .Q
       (\cache_data_way0[2] [2]));
  SDFFRHQX1 \cache_data_way0_reg[2][4] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [4]), .SE (n_248), .SI (n_242), .Q
       (\cache_data_way0[2] [4]));
  SDFFRHQX1 \cache_data_way0_reg[2][6] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [6]), .SE (n_248), .SI (n_243), .Q
       (\cache_data_way0[2] [6]));
  SDFFRHQX1 \cache_data_way0_reg[2][7] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [7]), .SE (n_248), .SI (n_240), .Q
       (\cache_data_way0[2] [7]));
  SDFFRHQX1 \cache_data_way0_reg[2][8] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [8]), .SE (n_248), .SI (data_in[1]), .Q
       (\cache_data_way0[2] [8]));
  SDFFRHQX1 \cache_data_way0_reg[2][10] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [10]), .SE (n_248), .SI (data_in[3]), .Q
       (\cache_data_way0[2] [10]));
  SDFFRHQX1 \cache_data_way0_reg[2][11] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [11]), .SE (n_248), .SI (data_in[4]), .Q
       (\cache_data_way0[2] [11]));
  SDFFRHQX1 \cache_data_way0_reg[2][12] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [12]), .SE (n_248), .SI (data_in[5]), .Q
       (\cache_data_way0[2] [12]));
  SDFFRHQX1 \cache_data_way0_reg[2][14] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [14]), .SE (n_248), .SI (data_in[7]), .Q
       (\cache_data_way0[2] [14]));
  SDFFRHQX1 \cache_data_way0_reg[2][15] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [15]), .SE (n_248), .SI (data_in[8]), .Q
       (\cache_data_way0[2] [15]));
  SDFFRHQX1 \cache_addr_way1_reg[2][2] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[2] [2]), .SE (n_245), .SI (address[2]), .Q
       (\cache_addr_way1[2] [2]));
  SDFFRHQX1 \cache_data_way0_reg[2][18] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [18]), .SE (n_248), .SI (data_in[11]), .Q
       (\cache_data_way0[2] [18]));
  SDFFRHQX1 \cache_addr_way1_reg[2][3] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[2] [3]), .SE (n_245), .SI (address[3]), .Q
       (\cache_addr_way1[2] [3]));
  SDFFRHQX1 \cache_data_way0_reg[2][19] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [19]), .SE (n_248), .SI (data_in[12]), .Q
       (\cache_data_way0[2] [19]));
  SDFFRHQX1 \cache_addr_way1_reg[2][4] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[2] [4]), .SE (n_245), .SI (address[4]), .Q
       (\cache_addr_way1[2] [4]));
  SDFFRHQX1 \cache_data_way0_reg[2][22] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [22]), .SE (n_248), .SI (data_in[15]), .Q
       (\cache_data_way0[2] [22]));
  SDFFRHQX1 \cache_data_way0_reg[2][23] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [23]), .SE (n_248), .SI (data_in[16]), .Q
       (\cache_data_way0[2] [23]));
  SDFFRHQX1 \cache_addr_way1_reg[3][1] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[3] [1]), .SE (n_247), .SI (address[1]), .Q
       (\cache_addr_way1[3] [1]));
  OAI21XL g25743__3680(.A0 (n_12), .A1 (n_250), .B0 (n_220), .Y
       (n_239));
  SDFFRHQX1 \cache_addr_way0_reg[2][4] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way0[2] [4]), .SE (n_248), .SI (address[4]), .Q
       (\cache_addr_way0[2] [4]));
  SDFFRHQX1 \cache_addr_way1_reg[3][3] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[3] [3]), .SE (n_247), .SI (address[3]), .Q
       (\cache_addr_way1[3] [3]));
  SDFFRHQX1 \cache_addr_way1_reg[3][4] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[3] [4]), .SE (n_247), .SI (address[4]), .Q
       (\cache_addr_way1[3] [4]));
  SDFFRHQX1 \cache_addr_way1_reg[3][5] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[3] [5]), .SE (n_247), .SI (address[5]), .Q
       (\cache_addr_way1[3] [5]));
  SDFFRHQX1 \cache_addr_way1_reg[4][1] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[4] [1]), .SE (n_241), .SI (address[1]), .Q
       (\cache_addr_way1[4] [1]));
  SDFFRHQX1 \cache_addr_way1_reg[4][2] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[4] [2]), .SE (n_241), .SI (address[2]), .Q
       (\cache_addr_way1[4] [2]));
  SDFFRHQX1 \cache_addr_way1_reg[4][3] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[4] [3]), .SE (n_241), .SI (address[3]), .Q
       (\cache_addr_way1[4] [3]));
  SDFFRHQX1 \cache_addr_way1_reg[4][4] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[4] [4]), .SE (n_241), .SI (address[4]), .Q
       (\cache_addr_way1[4] [4]));
  SDFFRHQX1 \cache_addr_way1_reg[4][5] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[4] [5]), .SE (n_241), .SI (address[5]), .Q
       (\cache_addr_way1[4] [5]));
  SDFFRHQX1 \cache_data_way0_reg[4][1] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [1]), .SE (n_246), .SI (n_238), .Q
       (\cache_data_way0[4] [1]));
  SDFFRHQX1 \cache_data_way0_reg[4][11] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [11]), .SE (n_246), .SI (data_in[4]), .Q
       (\cache_data_way0[4] [11]));
  SDFFRHQX1 \cache_data_way0_reg[4][3] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [3]), .SE (n_246), .SI (n_237), .Q
       (\cache_data_way0[4] [3]));
  SDFFRHQX1 \cache_data_way0_reg[4][5] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [5]), .SE (n_246), .SI (n_236), .Q
       (\cache_data_way0[4] [5]));
  SDFFRHQX1 \cache_data_way1_reg[3][16] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [16]), .SE (n_247), .SI (data_in[9]), .Q
       (\cache_data_way1[3] [16]));
  SDFFRHQX1 \cache_data_way0_reg[4][8] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [8]), .SE (n_246), .SI (data_in[1]), .Q
       (\cache_data_way0[4] [8]));
  SDFFRHQX1 \cache_data_way0_reg[4][10] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [10]), .SE (n_246), .SI (data_in[3]), .Q
       (\cache_data_way0[4] [10]));
  SDFFRHQX1 \cache_data_way0_reg[4][12] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [12]), .SE (n_246), .SI (data_in[5]), .Q
       (\cache_data_way0[4] [12]));
  SDFFRHQX1 \cache_data_way0_reg[4][14] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [14]), .SE (n_246), .SI (data_in[7]), .Q
       (\cache_data_way0[4] [14]));
  SDFFRHQX1 \cache_data_way0_reg[4][16] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [16]), .SE (n_246), .SI (data_in[9]), .Q
       (\cache_data_way0[4] [16]));
  SDFFRHQX1 \cache_data_way0_reg[4][18] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [18]), .SE (n_246), .SI (data_in[11]), .Q
       (\cache_data_way0[4] [18]));
  SDFFRHQX1 \cache_addr_way0_reg[2][6] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way0[2] [6]), .SE (n_248), .SI (address[6]), .Q
       (\cache_addr_way0[2] [6]));
  SDFFRHQX1 \cache_data_way0_reg[4][13] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [13]), .SE (n_246), .SI (data_in[6]), .Q
       (\cache_data_way0[4] [13]));
  SDFFRHQX1 \cache_data_way1_reg[3][3] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [3]), .SE (n_247), .SI (n_237), .Q
       (\cache_data_way1[3] [3]));
  SDFFRHQX1 \cache_data_way0_reg[4][15] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [15]), .SE (n_246), .SI (data_in[8]), .Q
       (\cache_data_way0[4] [15]));
  SDFFRHQX1 \cache_data_way1_reg[2][3] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [3]), .SE (n_245), .SI (n_237), .Q
       (\cache_data_way1[2] [3]));
  SDFFRHQX1 \cache_data_way1_reg[4][12] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [12]), .SE (n_241), .SI (data_in[5]), .Q
       (\cache_data_way1[4] [12]));
  SDFFRHQX1 \cache_data_way1_reg[3][7] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [7]), .SE (n_247), .SI (n_240), .Q
       (\cache_data_way1[3] [7]));
  SDFFRHQX1 \cache_data_way1_reg[4][5] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [5]), .SE (n_241), .SI (n_236), .Q
       (\cache_data_way1[4] [5]));
  SDFFRHQX1 \cache_data_way1_reg[4][14] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [14]), .SE (n_241), .SI (data_in[7]), .Q
       (\cache_data_way1[4] [14]));
  SDFFRHQX1 \cache_data_way0_reg[2][1] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [1]), .SE (n_248), .SI (n_238), .Q
       (\cache_data_way0[2] [1]));
  SDFFRHQX1 \cache_data_way0_reg[2][17] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [17]), .SE (n_248), .SI (data_in[10]), .Q
       (\cache_data_way0[2] [17]));
  SDFFRHQX1 \cache_addr_way0_reg[4][4] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way0[4] [4]), .SE (n_246), .SI (address[4]), .Q
       (\cache_addr_way0[4] [4]));
  SDFFRHQX1 \cache_addr_way0_reg[4][2] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way0[4] [2]), .SE (n_246), .SI (address[2]), .Q
       (\cache_addr_way0[4] [2]));
  SDFFRHQX1 \cache_data_way1_reg[4][8] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [8]), .SE (n_241), .SI (data_in[1]), .Q
       (\cache_data_way1[4] [8]));
  SDFFRHQX1 \cache_addr_way1_reg[3][2] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[3] [2]), .SE (n_247), .SI (address[2]), .Q
       (\cache_addr_way1[3] [2]));
  SDFFRHQX1 \cache_data_way1_reg[3][5] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [5]), .SE (n_247), .SI (n_236), .Q
       (\cache_data_way1[3] [5]));
  SDFFRHQX1 \cache_data_way1_reg[3][22] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [22]), .SE (n_247), .SI (data_in[15]), .Q
       (\cache_data_way1[3] [22]));
  SDFFRHQX1 \cache_addr_way1_reg[2][1] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[2] [1]), .SE (n_245), .SI (address[1]), .Q
       (\cache_addr_way1[2] [1]));
  SDFFRHQX1 \cache_data_way1_reg[2][22] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [22]), .SE (n_245), .SI (data_in[15]), .Q
       (\cache_data_way1[2] [22]));
  SDFFRHQX1 \cache_data_way1_reg[4][3] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [3]), .SE (n_241), .SI (n_237), .Q
       (\cache_data_way1[4] [3]));
  SDFFRHQX1 \cache_data_way1_reg[4][7] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [7]), .SE (n_241), .SI (n_240), .Q
       (\cache_data_way1[4] [7]));
  SDFFRHQX1 \cache_data_way0_reg[4][9] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [9]), .SE (n_246), .SI (data_in[2]), .Q
       (\cache_data_way0[4] [9]));
  SDFFRHQX1 \cache_data_way1_reg[4][1] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [1]), .SE (n_241), .SI (n_238), .Q
       (\cache_data_way1[4] [1]));
  SDFFRHQX1 \cache_data_way1_reg[3][1] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [1]), .SE (n_247), .SI (n_238), .Q
       (\cache_data_way1[3] [1]));
  SDFFRHQX1 \cache_data_way0_reg[2][13] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [13]), .SE (n_248), .SI (data_in[6]), .Q
       (\cache_data_way0[2] [13]));
  SDFFRHQX1 \cache_data_way0_reg[4][7] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [7]), .SE (n_246), .SI (n_240), .Q
       (\cache_data_way0[4] [7]));
  SDFFRHQX1 \cache_data_way1_reg[2][20] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [20]), .SE (n_245), .SI (data_in[13]), .Q
       (\cache_data_way1[2] [20]));
  SDFFRHQX1 \cache_data_way0_reg[2][5] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [5]), .SE (n_248), .SI (n_236), .Q
       (\cache_data_way0[2] [5]));
  SDFFRHQX1 \cache_data_way0_reg[4][4] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [4]), .SE (n_246), .SI (n_242), .Q
       (\cache_data_way0[4] [4]));
  SDFFRHQX1 \cache_data_way1_reg[2][17] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [17]), .SE (n_245), .SI (data_in[10]), .Q
       (\cache_data_way1[2] [17]));
  SDFFRHQX1 \cache_data_way0_reg[2][20] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [20]), .SE (n_248), .SI (data_in[13]), .Q
       (\cache_data_way0[2] [20]));
  SDFFRHQX1 \cache_data_way0_reg[2][9] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [9]), .SE (n_248), .SI (data_in[2]), .Q
       (\cache_data_way0[2] [9]));
  SDFFRHQX1 \cache_addr_way1_reg[2][6] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[2] [6]), .SE (n_245), .SI (address[6]), .Q
       (\cache_addr_way1[2] [6]));
  SDFFRHQX1 \cache_data_way1_reg[2][15] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [15]), .SE (n_245), .SI (data_in[8]), .Q
       (\cache_data_way1[2] [15]));
  SDFFRHQX1 \cache_data_way1_reg[3][18] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [18]), .SE (n_247), .SI (data_in[11]), .Q
       (\cache_data_way1[3] [18]));
  SDFFRHQX1 \cache_addr_way0_reg[2][1] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way0[2] [1]), .SE (n_248), .SI (address[1]), .Q
       (\cache_addr_way0[2] [1]));
  SDFFRHQX1 \cache_data_way1_reg[3][20] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [20]), .SE (n_247), .SI (data_in[13]), .Q
       (\cache_data_way1[3] [20]));
  SDFFRHQX1 \cache_data_way1_reg[2][21] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [21]), .SE (n_245), .SI (data_in[14]), .Q
       (\cache_data_way1[2] [21]));
  SDFFRHQX1 \cache_data_way0_reg[4][23] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [23]), .SE (n_246), .SI (data_in[16]), .Q
       (\cache_data_way0[4] [23]));
  SDFFRHQX1 \cache_data_way0_reg[4][17] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [17]), .SE (n_246), .SI (data_in[10]), .Q
       (\cache_data_way0[4] [17]));
  SDFFRHQX1 \cache_data_way1_reg[3][15] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[3] [15]), .SE (n_247), .SI (data_in[8]), .Q
       (\cache_data_way1[3] [15]));
  SDFFRHQX1 \cache_data_way1_reg[2][9] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [9]), .SE (n_245), .SI (data_in[2]), .Q
       (\cache_data_way1[2] [9]));
  SDFFRHQX1 \cache_data_way1_reg[4][10] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [10]), .SE (n_241), .SI (data_in[3]), .Q
       (\cache_data_way1[4] [10]));
  SDFFRHQX1 \cache_data_way1_reg[4][18] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [18]), .SE (n_241), .SI (data_in[11]), .Q
       (\cache_data_way1[4] [18]));
  SDFFRHQX1 \cache_data_way0_reg[4][21] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [21]), .SE (n_246), .SI (data_in[14]), .Q
       (\cache_data_way0[4] [21]));
  SDFFRHQX1 \cache_data_way1_reg[2][13] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [13]), .SE (n_245), .SI (data_in[6]), .Q
       (\cache_data_way1[2] [13]));
  SDFFRHQX1 \cache_data_way1_reg[4][22] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[4] [22]), .SE (n_241), .SI (data_in[15]), .Q
       (\cache_data_way1[4] [22]));
  SDFFRHQX1 \cache_data_way0_reg[2][21] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[2] [21]), .SE (n_248), .SI (data_in[14]), .Q
       (\cache_data_way0[2] [21]));
  SDFFRHQX1 \cache_data_way0_reg[4][2] (.RN (n_272), .CK (clk), .D
       (\cache_data_way0[4] [2]), .SE (n_246), .SI (n_244), .Q
       (\cache_data_way0[4] [2]));
  SDFFRHQX1 \cache_data_way1_reg[2][11] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[2] [11]), .SE (n_245), .SI (data_in[4]), .Q
       (\cache_data_way1[2] [11]));
  OAI21XL g25893__1617(.A0 (address[6]), .A1 (n_137), .B0
       (\cache_lru[1] ), .Y (n_235));
  NAND4BX1 g25594__2802(.AN (n_181), .B (n_124), .C (n_179), .D
       (n_180), .Y (n_234));
  SDFFRHQX1 \cache_addr_way0_reg[3][5] (.RN (n_272), .CK (clk), .D
       (address[5]), .SE (n_591), .SI (\cache_addr_way0[3] [5]), .Q
       (\cache_addr_way0[3] [5]));
  SDFFRHQX1 \cache_data_way0_reg[3][7] (.RN (n_272), .CK (clk), .D
       (n_240), .SE (n_591), .SI (\cache_data_way0[3] [7]), .Q
       (\cache_data_way0[3] [7]));
  SDFFRHQX1 \cache_addr_way0_reg[3][2] (.RN (n_272), .CK (clk), .D
       (address[2]), .SE (n_591), .SI (\cache_addr_way0[3] [2]), .Q
       (\cache_addr_way0[3] [2]));
  SDFFRHQX1 \cache_addr_way0_reg[3][4] (.RN (n_272), .CK (clk), .D
       (address[4]), .SE (n_591), .SI (\cache_addr_way0[3] [4]), .Q
       (\cache_addr_way0[3] [4]));
  SDFFRHQX1 \cache_data_way0_reg[3][8] (.RN (n_272), .CK (clk), .D
       (data_in[1]), .SE (n_591), .SI (\cache_data_way0[3] [8]), .Q
       (\cache_data_way0[3] [8]));
  SDFFRHQX1 \cache_data_way0_reg[3][11] (.RN (n_272), .CK (clk), .D
       (data_in[4]), .SE (n_591), .SI (\cache_data_way0[3] [11]), .Q
       (\cache_data_way0[3] [11]));
  SDFFRHQX1 \cache_data_way0_reg[3][13] (.RN (n_272), .CK (clk), .D
       (data_in[6]), .SE (n_591), .SI (\cache_data_way0[3] [13]), .Q
       (\cache_data_way0[3] [13]));
  SDFFRHQX1 \cache_data_way0_reg[3][15] (.RN (n_272), .CK (clk), .D
       (data_in[8]), .SE (n_591), .SI (\cache_data_way0[3] [15]), .Q
       (\cache_data_way0[3] [15]));
  SDFFRHQX1 \cache_data_way0_reg[3][19] (.RN (n_272), .CK (clk), .D
       (data_in[12]), .SE (n_591), .SI (\cache_data_way0[3] [19]), .Q
       (\cache_data_way0[3] [19]));
  SDFFRHQX1 \cache_data_way0_reg[3][22] (.RN (n_272), .CK (clk), .D
       (data_in[15]), .SE (n_591), .SI (\cache_data_way0[3] [22]), .Q
       (\cache_data_way0[3] [22]));
  SDFFRHQX1 \cache_addr_way0_reg[3][1] (.RN (n_272), .CK (clk), .D
       (address[1]), .SE (n_591), .SI (\cache_addr_way0[3] [1]), .Q
       (\cache_addr_way0[3] [1]));
  SDFFRHQX1 \cache_data_way0_reg[3][20] (.RN (n_272), .CK (clk), .D
       (data_in[13]), .SE (n_591), .SI (\cache_data_way0[3] [20]), .Q
       (\cache_data_way0[3] [20]));
  SDFFRHQX1 \cache_data_way0_reg[3][21] (.RN (n_272), .CK (clk), .D
       (data_in[14]), .SE (n_591), .SI (\cache_data_way0[3] [21]), .Q
       (\cache_data_way0[3] [21]));
  SDFFRHQX1 \cache_data_way0_reg[3][6] (.RN (n_272), .CK (clk), .D
       (n_243), .SE (n_591), .SI (\cache_data_way0[3] [6]), .Q
       (\cache_data_way0[3] [6]));
  SDFFRHQX1 \cache_data_way0_reg[3][16] (.RN (n_272), .CK (clk), .D
       (data_in[9]), .SE (n_591), .SI (\cache_data_way0[3] [16]), .Q
       (\cache_data_way0[3] [16]));
  SDFFRHQX1 \cache_data_way0_reg[3][2] (.RN (n_272), .CK (clk), .D
       (n_244), .SE (n_591), .SI (\cache_data_way0[3] [2]), .Q
       (\cache_data_way0[3] [2]));
  SDFFRHQX1 \cache_data_way0_reg[3][3] (.RN (n_272), .CK (clk), .D
       (n_237), .SE (n_591), .SI (\cache_data_way0[3] [3]), .Q
       (\cache_data_way0[3] [3]));
  SDFFRHQX1 \cache_data_way0_reg[3][5] (.RN (n_272), .CK (clk), .D
       (n_236), .SE (n_591), .SI (\cache_data_way0[3] [5]), .Q
       (\cache_data_way0[3] [5]));
  NAND4BX1 g25608__1705(.AN (n_173), .B (n_109), .C (n_160), .D
       (n_159), .Y (n_232));
  NAND4BX1 g25601__5122(.AN (n_135), .B (n_119), .C (n_201), .D
       (n_174), .Y (n_231));
  NAND4BX1 g25602__8246(.AN (n_126), .B (n_118), .C (n_170), .D
       (n_154), .Y (n_230));
  NAND4BX1 g25605__7098(.AN (n_200), .B (n_115), .C (n_165), .D (n_80),
       .Y (n_229));
  NAND4BX1 g25607__6131(.AN (n_134), .B (n_111), .C (n_162), .D (n_82),
       .Y (n_228));
  NAND4BX1 g25599__1881(.AN (n_127), .B (n_110), .C (n_142), .D
       (n_145), .Y (n_227));
  NAND4BX1 g25610__5115(.AN (n_114), .B (n_125), .C (n_166), .D
       (n_167), .Y (n_226));
  NAND4BX1 g25612__7482(.AN (n_128), .B (n_102), .C (n_148), .D
       (n_175), .Y (n_225));
  NAND4BX1 g25614__4733(.AN (n_198), .B (n_123), .C (n_171), .D (n_77),
       .Y (n_224));
  OAI21XL g25894__6161(.A0 (address[6]), .A1 (n_588), .B0
       (\cache_lru[3] ), .Y (n_223));
  NAND4BX1 g25598__9315(.AN (n_113), .B (n_117), .C (n_168), .D
       (n_169), .Y (n_222));
  SDFFRHQX1 \cache_data_way0_reg[3][12] (.RN (n_272), .CK (clk), .D
       (data_in[5]), .SE (n_591), .SI (\cache_data_way0[3] [12]), .Q
       (\cache_data_way0[3] [12]));
  SDFFRHQX1 \cache_data_way0_reg[3][17] (.RN (n_272), .CK (clk), .D
       (data_in[10]), .SE (n_591), .SI (\cache_data_way0[3] [17]), .Q
       (\cache_data_way0[3] [17]));
  SDFFRHQX1 \cache_data_way0_reg[3][4] (.RN (n_272), .CK (clk), .D
       (n_242), .SE (n_591), .SI (\cache_data_way0[3] [4]), .Q
       (\cache_data_way0[3] [4]));
  SDFFRHQX1 \cache_data_way0_reg[3][10] (.RN (n_272), .CK (clk), .D
       (data_in[3]), .SE (n_591), .SI (\cache_data_way0[3] [10]), .Q
       (\cache_data_way0[3] [10]));
  SDFFRHQX1 \cache_data_way0_reg[3][1] (.RN (n_272), .CK (clk), .D
       (n_238), .SE (n_591), .SI (\cache_data_way0[3] [1]), .Q
       (\cache_data_way0[3] [1]));
  SDFFRHQX1 \cache_data_way0_reg[3][18] (.RN (n_272), .CK (clk), .D
       (data_in[11]), .SE (n_591), .SI (\cache_data_way0[3] [18]), .Q
       (\cache_data_way0[3] [18]));
  SDFFRHQX1 \cache_data_way0_reg[3][14] (.RN (n_272), .CK (clk), .D
       (data_in[7]), .SE (n_591), .SI (\cache_data_way0[3] [14]), .Q
       (\cache_data_way0[3] [14]));
  SDFFRHQX1 \cache_data_way0_reg[3][23] (.RN (n_272), .CK (clk), .D
       (data_in[16]), .SE (n_591), .SI (\cache_data_way0[3] [23]), .Q
       (\cache_data_way0[3] [23]));
  SDFFRHQX1 \cache_data_way0_reg[3][9] (.RN (n_272), .CK (clk), .D
       (data_in[2]), .SE (n_591), .SI (\cache_data_way0[3] [9]), .Q
       (\cache_data_way0[3] [9]));
  SDFFRHQX1 \cache_addr_way0_reg[3][3] (.RN (n_272), .CK (clk), .D
       (address[3]), .SE (n_591), .SI (\cache_addr_way0[3] [3]), .Q
       (\cache_addr_way0[3] [3]));
  OAI2BB1X1 g25887__9945(.A0N (\cache_data_way0[2] [20]), .A1N (n_217),
       .B0 (n_185), .Y (n_221));
  OAI2BB1X1 g25868__2883(.A0N (address[6]), .A1N (n_136), .B0
       (\cache_lru[2] ), .Y (n_220));
  OAI2BB1X1 g25870__2346(.A0N (\cache_data_way0[4] [2]), .A1N (n_215),
       .B0 (n_197), .Y (n_219));
  OAI2BB1X1 g25888__1666(.A0N (\cache_data_way0[2] [10]), .A1N (n_217),
       .B0 (n_190), .Y (n_218));
  OAI2BB1X1 g25889__7410(.A0N (\cache_data_way0[4] [21]), .A1N (n_215),
       .B0 (n_184), .Y (n_216));
  SDFFRHQX1 \cache_data_way1_reg[1][1] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [1]), .SE (n_214), .SI (n_238), .Q
       (\cache_data_way1[1] [1]));
  SDFFRHQX1 \cache_data_way1_reg[1][3] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [3]), .SE (n_214), .SI (n_237), .Q
       (\cache_data_way1[1] [3]));
  SDFFRHQX1 \cache_data_way1_reg[1][5] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [5]), .SE (n_214), .SI (n_236), .Q
       (\cache_data_way1[1] [5]));
  SDFFRHQX1 \cache_data_way1_reg[1][7] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [7]), .SE (n_214), .SI (n_240), .Q
       (\cache_data_way1[1] [7]));
  SDFFRHQX1 \cache_data_way1_reg[1][9] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [9]), .SE (n_214), .SI (data_in[2]), .Q
       (\cache_data_way1[1] [9]));
  SDFFRHQX1 \cache_data_way1_reg[1][11] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [11]), .SE (n_214), .SI (data_in[4]), .Q
       (\cache_data_way1[1] [11]));
  SDFFRHQX1 \cache_data_way1_reg[1][13] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [13]), .SE (n_214), .SI (data_in[6]), .Q
       (\cache_data_way1[1] [13]));
  SDFFRHQX1 \cache_data_way1_reg[1][15] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [15]), .SE (n_214), .SI (data_in[8]), .Q
       (\cache_data_way1[1] [15]));
  SDFFRHQX1 \cache_data_way1_reg[1][17] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [17]), .SE (n_214), .SI (data_in[10]), .Q
       (\cache_data_way1[1] [17]));
  SDFFRHQX1 \cache_data_way1_reg[1][19] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [19]), .SE (n_214), .SI (data_in[12]), .Q
       (\cache_data_way1[1] [19]));
  SDFFRHQX1 \cache_data_way1_reg[1][21] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [21]), .SE (n_214), .SI (data_in[14]), .Q
       (\cache_data_way1[1] [21]));
  SDFFRHQX1 \cache_addr_way1_reg[1][4] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[1] [4]), .SE (n_214), .SI (address[4]), .Q
       (\cache_addr_way1[1] [4]));
  SDFFRHQX1 \cache_addr_way0_reg[1][1] (.RN (n_272), .CK (clk), .D
       (address[1]), .SE (n_213), .SI (\cache_addr_way0[1] [1]), .Q
       (\cache_addr_way0[1] [1]));
  SDFFRHQX1 \cache_addr_way1_reg[1][3] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[1] [3]), .SE (n_214), .SI (address[3]), .Q
       (\cache_addr_way1[1] [3]));
  SDFFRHQX1 \cache_addr_way0_reg[1][4] (.RN (n_272), .CK (clk), .D
       (address[4]), .SE (n_213), .SI (\cache_addr_way0[1] [4]), .Q
       (\cache_addr_way0[1] [4]));
  SDFFRHQX1 \cache_data_way0_reg[1][3] (.RN (n_272), .CK (clk), .D
       (n_237), .SE (n_213), .SI (\cache_data_way0[1] [3]), .Q
       (\cache_data_way0[1] [3]));
  SDFFRHQX1 \cache_data_way0_reg[1][5] (.RN (n_272), .CK (clk), .D
       (n_236), .SE (n_213), .SI (\cache_data_way0[1] [5]), .Q
       (\cache_data_way0[1] [5]));
  SDFFRHQX1 \cache_data_way1_reg[1][10] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [10]), .SE (n_214), .SI (data_in[3]), .Q
       (\cache_data_way1[1] [10]));
  SDFFRHQX1 \cache_data_way0_reg[1][9] (.RN (n_272), .CK (clk), .D
       (data_in[2]), .SE (n_213), .SI (\cache_data_way0[1] [9]), .Q
       (\cache_data_way0[1] [9]));
  SDFFRHQX1 \cache_data_way0_reg[1][11] (.RN (n_272), .CK (clk), .D
       (data_in[4]), .SE (n_213), .SI (\cache_data_way0[1] [11]), .Q
       (\cache_data_way0[1] [11]));
  SDFFRHQX1 \cache_data_way0_reg[1][13] (.RN (n_272), .CK (clk), .D
       (data_in[6]), .SE (n_213), .SI (\cache_data_way0[1] [13]), .Q
       (\cache_data_way0[1] [13]));
  SDFFRHQX1 \cache_data_way0_reg[1][18] (.RN (n_272), .CK (clk), .D
       (data_in[11]), .SE (n_213), .SI (\cache_data_way0[1] [18]), .Q
       (\cache_data_way0[1] [18]));
  SDFFRHQX1 \cache_data_way0_reg[1][17] (.RN (n_272), .CK (clk), .D
       (data_in[10]), .SE (n_213), .SI (\cache_data_way0[1] [17]), .Q
       (\cache_data_way0[1] [17]));
  SDFFRHQX1 \cache_data_way0_reg[1][19] (.RN (n_272), .CK (clk), .D
       (data_in[12]), .SE (n_213), .SI (\cache_data_way0[1] [19]), .Q
       (\cache_data_way0[1] [19]));
  SDFFRHQX1 \cache_data_way0_reg[1][21] (.RN (n_272), .CK (clk), .D
       (data_in[14]), .SE (n_213), .SI (\cache_data_way0[1] [21]), .Q
       (\cache_data_way0[1] [21]));
  SDFFRHQX1 \cache_data_way0_reg[1][23] (.RN (n_272), .CK (clk), .D
       (data_in[16]), .SE (n_213), .SI (\cache_data_way0[1] [23]), .Q
       (\cache_data_way0[1] [23]));
  SDFFRHQX1 \cache_data_way0_reg[1][4] (.RN (n_272), .CK (clk), .D
       (n_242), .SE (n_213), .SI (\cache_data_way0[1] [4]), .Q
       (\cache_data_way0[1] [4]));
  SDFFRHQX1 \cache_data_way0_reg[1][10] (.RN (n_272), .CK (clk), .D
       (data_in[3]), .SE (n_213), .SI (\cache_data_way0[1] [10]), .Q
       (\cache_data_way0[1] [10]));
  OAI2BB1X1 g25871__6417(.A0N (\cache_data_way0[4] [3]), .A1N (n_215),
       .B0 (n_191), .Y (n_212));
  OAI2BB1X1 g25873__5477(.A0N (\cache_data_way0[3] [6]), .A1N (n_209),
       .B0 (n_183), .Y (n_211));
  OAI2BB1X1 g25875__2398(.A0N (\cache_data_way0[3] [8]), .A1N (n_209),
       .B0 (n_196), .Y (n_210));
  OAI2BB1X1 g25886__5107(.A0N (\cache_data_way0[2] [19]), .A1N (n_217),
       .B0 (n_186), .Y (n_208));
  OAI2BB1X1 g25891__6260(.A0N (\cache_data_way0[3] [23]), .A1N (n_209),
       .B0 (n_182), .Y (n_207));
  OAI2BB1X1 g25874__4319(.A0N (\cache_data_way0[4] [7]), .A1N (n_215),
       .B0 (n_194), .Y (n_206));
  OAI2BB1X1 g25884__8428(.A0N (\cache_data_way0[3] [5]), .A1N (n_209),
       .B0 (n_189), .Y (n_205));
  OAI2BB1X1 g25882__5526(.A0N (\cache_data_way1[1] [16]), .A1N (n_199),
       .B0 (n_188), .Y (n_204));
  SDFFRHQX1 \cache_data_way0_reg[1][2] (.RN (n_272), .CK (clk), .D
       (n_244), .SE (n_213), .SI (\cache_data_way0[1] [2]), .Q
       (\cache_data_way0[1] [2]));
  SDFFRHQX1 \cache_data_way1_reg[1][23] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [23]), .SE (n_214), .SI (data_in[16]), .Q
       (\cache_data_way1[1] [23]));
  SDFFRHQX1 \cache_data_way0_reg[1][20] (.RN (n_272), .CK (clk), .D
       (data_in[13]), .SE (n_213), .SI (\cache_data_way0[1] [20]), .Q
       (\cache_data_way0[1] [20]));
  SDFFRHQX1 \cache_addr_way0_reg[1][3] (.RN (n_272), .CK (clk), .D
       (address[3]), .SE (n_213), .SI (\cache_addr_way0[1] [3]), .Q
       (\cache_addr_way0[1] [3]));
  SDFFRHQX1 \cache_data_way1_reg[1][20] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [20]), .SE (n_214), .SI (data_in[13]), .Q
       (\cache_data_way1[1] [20]));
  SDFFRHQX1 \cache_data_way1_reg[1][18] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [18]), .SE (n_214), .SI (data_in[11]), .Q
       (\cache_data_way1[1] [18]));
  SDFFRHQX1 \cache_data_way0_reg[1][1] (.RN (n_272), .CK (clk), .D
       (n_238), .SE (n_213), .SI (\cache_data_way0[1] [1]), .Q
       (\cache_data_way0[1] [1]));
  SDFFRHQX1 \cache_addr_way0_reg[1][2] (.RN (n_272), .CK (clk), .D
       (address[2]), .SE (n_213), .SI (\cache_addr_way0[1] [2]), .Q
       (\cache_addr_way0[1] [2]));
  SDFFRHQX1 \cache_data_way1_reg[1][16] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [16]), .SE (n_214), .SI (data_in[9]), .Q
       (\cache_data_way1[1] [16]));
  SDFFRHQX1 \cache_data_way1_reg[1][12] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [12]), .SE (n_214), .SI (data_in[5]), .Q
       (\cache_data_way1[1] [12]));
  SDFFRHQX1 \cache_data_way0_reg[1][16] (.RN (n_272), .CK (clk), .D
       (data_in[9]), .SE (n_213), .SI (\cache_data_way0[1] [16]), .Q
       (\cache_data_way0[1] [16]));
  SDFFRHQX1 \cache_data_way1_reg[1][14] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [14]), .SE (n_214), .SI (data_in[7]), .Q
       (\cache_data_way1[1] [14]));
  SDFFRHQX1 \cache_data_way1_reg[1][8] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [8]), .SE (n_214), .SI (data_in[1]), .Q
       (\cache_data_way1[1] [8]));
  SDFFRHQX1 \cache_data_way0_reg[1][6] (.RN (n_272), .CK (clk), .D
       (n_243), .SE (n_213), .SI (\cache_data_way0[1] [6]), .Q
       (\cache_data_way0[1] [6]));
  SDFFRHQX1 \cache_data_way0_reg[1][14] (.RN (n_272), .CK (clk), .D
       (data_in[7]), .SE (n_213), .SI (\cache_data_way0[1] [14]), .Q
       (\cache_data_way0[1] [14]));
  SDFFRHQX1 \cache_data_way1_reg[1][2] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [2]), .SE (n_214), .SI (n_244), .Q
       (\cache_data_way1[1] [2]));
  SDFFRHQX1 \cache_data_way0_reg[1][15] (.RN (n_272), .CK (clk), .D
       (data_in[8]), .SE (n_213), .SI (\cache_data_way0[1] [15]), .Q
       (\cache_data_way0[1] [15]));
  SDFFRHQX1 \cache_data_way0_reg[1][7] (.RN (n_272), .CK (clk), .D
       (n_240), .SE (n_213), .SI (\cache_data_way0[1] [7]), .Q
       (\cache_data_way0[1] [7]));
  SDFFRHQX1 \cache_data_way1_reg[1][6] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [6]), .SE (n_214), .SI (n_243), .Q
       (\cache_data_way1[1] [6]));
  SDFFRHQX1 \cache_data_way1_reg[1][4] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [4]), .SE (n_214), .SI (n_242), .Q
       (\cache_data_way1[1] [4]));
  SDFFRHQX1 \cache_addr_way1_reg[1][2] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[1] [2]), .SE (n_214), .SI (address[2]), .Q
       (\cache_addr_way1[1] [2]));
  SDFFRHQX1 \cache_data_way0_reg[1][12] (.RN (n_272), .CK (clk), .D
       (data_in[5]), .SE (n_213), .SI (\cache_data_way0[1] [12]), .Q
       (\cache_data_way0[1] [12]));
  SDFFRHQX1 \cache_data_way0_reg[1][8] (.RN (n_272), .CK (clk), .D
       (data_in[1]), .SE (n_213), .SI (\cache_data_way0[1] [8]), .Q
       (\cache_data_way0[1] [8]));
  SDFFRHQX1 \cache_addr_way1_reg[1][1] (.RN (n_272), .CK (clk), .D
       (\cache_addr_way1[1] [1]), .SE (n_214), .SI (address[1]), .Q
       (\cache_addr_way1[1] [1]));
  SDFFRHQX1 \cache_data_way1_reg[1][22] (.RN (n_272), .CK (clk), .D
       (\cache_data_way1[1] [22]), .SE (n_214), .SI (data_in[15]), .Q
       (\cache_data_way1[1] [22]));
  SDFFRHQX1 \cache_data_way0_reg[1][22] (.RN (n_272), .CK (clk), .D
       (data_in[15]), .SE (n_213), .SI (\cache_data_way0[1] [22]), .Q
       (\cache_data_way0[1] [22]));
  NAND2X4 g25927__6783(.A (hit), .B (read_en), .Y (n_252));
  INVX1 g25980(.A (n_588), .Y (n_203));
  AOI22X1 g25919__3680(.A0 (\cache_data_way1[3] [11]), .A1 (n_195), .B0
       (\cache_data_way1[4] [11]), .B1 (n_178), .Y (n_201));
  OAI2BB1X1 g25881__1617(.A0N (\cache_data_way1[1] [15]), .A1N (n_199),
       .B0 (n_101), .Y (n_200));
  OAI2BB1X1 g25892__2802(.A0N (\cache_data_way1[1] [1]), .A1N (n_199),
       .B0 (n_99), .Y (n_198));
  AOI222X1 g25896__1705(.A0 (cache_codeword[2]), .A1 (n_590), .B0
       (\cache_data_way0[3] [2]), .B1 (n_209), .C0
       (\cache_data_way1[2] [2]), .C1 (n_192), .Y (n_197));
  AOI222X1 g25897__5122(.A0 (\cache_data_way0[2] [8]), .A1 (n_217), .B0
       (\cache_data_way0[4] [8]), .B1 (n_215), .C0
       (\cache_data_way1[3] [8]), .C1 (n_195), .Y (n_196));
  AOI222X1 g25898__8246(.A0 (cache_codeword[7]), .A1 (n_590), .B0
       (\cache_data_way0[2] [7]), .B1 (n_217), .C0
       (\cache_data_way1[2] [7]), .C1 (n_192), .Y (n_194));
  AOI222X1 g25899__7098(.A0 (cache_codeword[3]), .A1 (n_590), .B0
       (\cache_data_way0[2] [3]), .B1 (n_217), .C0
       (\cache_data_way1[3] [3]), .C1 (n_195), .Y (n_191));
  AOI222X1 g25900__6131(.A0 (cache_codeword[10]), .A1 (n_590), .B0
       (\cache_data_way0[3] [10]), .B1 (n_209), .C0
       (\cache_data_way1[2] [10]), .C1 (n_192), .Y (n_190));
  AOI222X1 g25902__1881(.A0 (cache_codeword[5]), .A1 (n_590), .B0
       (\cache_data_way0[2] [5]), .B1 (n_217), .C0
       (\cache_data_way1[3] [5]), .C1 (n_195), .Y (n_189));
  AOI222X1 g25908__5115(.A0 (cache_codeword[16]), .A1 (n_590), .B0
       (\cache_data_way0[4] [16]), .B1 (n_215), .C0
       (\cache_data_way1[2] [16]), .C1 (n_192), .Y (n_188));
  AOI22X1 g25911__7482(.A0 (\cache_data_way1[2] [3]), .A1 (n_192), .B0
       (\cache_data_way0[1] [3]), .B1 (n_163), .Y (n_187));
  AOI222X1 g25912__4733(.A0 (cache_codeword[19]), .A1 (n_590), .B0
       (\cache_data_way0[3] [19]), .B1 (n_209), .C0
       (\cache_data_way1[2] [19]), .C1 (n_192), .Y (n_186));
  AOI222X1 g25913__6161(.A0 (\cache_data_way0[3] [20]), .A1 (n_209),
       .B0 (\cache_data_way0[4] [20]), .B1 (n_215), .C0
       (\cache_data_way1[3] [20]), .C1 (n_195), .Y (n_185));
  AOI222X1 g25914__9315(.A0 (cache_codeword[21]), .A1 (n_590), .B0
       (\cache_data_way0[3] [21]), .B1 (n_209), .C0
       (\cache_data_way1[3] [21]), .C1 (n_195), .Y (n_184));
  AOI222X1 g25915__9945(.A0 (\cache_data_way0[2] [6]), .A1 (n_217), .B0
       (\cache_data_way0[4] [6]), .B1 (n_215), .C0
       (\cache_data_way1[3] [6]), .C1 (n_195), .Y (n_183));
  AOI222X1 g25917__2883(.A0 (cache_codeword[23]), .A1 (n_590), .B0
       (\cache_data_way0[2] [23]), .B1 (n_217), .C0
       (\cache_data_way1[3] [23]), .C1 (n_195), .Y (n_182));
  OAI2BB1X1 g25872__2346(.A0N (\cache_data_way0[4] [4]), .A1N (n_215),
       .B0 (n_96), .Y (n_181));
  AOI22X1 g25920__1666(.A0 (\cache_data_way1[1] [4]), .A1 (n_199), .B0
       (\cache_data_way0[2] [4]), .B1 (n_217), .Y (n_180));
  AOI22X1 g25921__7410(.A0 (\cache_data_way1[2] [4]), .A1 (n_192), .B0
       (\cache_data_way1[4] [4]), .B1 (n_178), .Y (n_179));
  AOI22X1 g25922__6417(.A0 (\cache_data_way1[1] [10]), .A1 (n_199), .B0
       (\cache_data_way0[4] [10]), .B1 (n_215), .Y (n_177));
  AOI22X1 g25923__5477(.A0 (\cache_data_way1[1] [2]), .A1 (n_199), .B0
       (\cache_data_way0[2] [2]), .B1 (n_217), .Y (n_176));
  AOI22X1 g25924__2398(.A0 (\cache_data_way1[3] [22]), .A1 (n_195), .B0
       (\cache_data_way1[4] [22]), .B1 (n_178), .Y (n_175));
  AOI22X1 g25925__5107(.A0 (\cache_data_way1[1] [11]), .A1 (n_199), .B0
       (\cache_data_way0[3] [11]), .B1 (n_209), .Y (n_174));
  OAI2BB1X1 g25885__6260(.A0N (\cache_data_way0[3] [18]), .A1N (n_209),
       .B0 (n_97), .Y (n_173));
  AOI22X1 g25926__4319(.A0 (\cache_data_way1[1] [7]), .A1 (n_199), .B0
       (\cache_data_way0[3] [7]), .B1 (n_209), .Y (n_172));
  AOI22X1 g25928__8428(.A0 (\cache_data_way1[3] [1]), .A1 (n_195), .B0
       (\cache_data_way1[4] [1]), .B1 (n_178), .Y (n_171));
  AOI22X1 g25929__5526(.A0 (\cache_data_way1[1] [12]), .A1 (n_199), .B0
       (cache_codeword[12]), .B1 (n_590), .Y (n_170));
  AOI22X1 g25930__6783(.A0 (\cache_data_way1[3] [13]), .A1 (n_195), .B0
       (\cache_data_way1[4] [13]), .B1 (n_178), .Y (n_169));
  AOI22X1 g25931__3680(.A0 (\cache_data_way1[1] [13]), .A1 (n_199), .B0
       (cache_codeword[13]), .B1 (n_590), .Y (n_168));
  AOI22X1 g25932__1617(.A0 (\cache_data_way1[2] [14]), .A1 (n_192), .B0
       (\cache_data_way1[4] [14]), .B1 (n_178), .Y (n_167));
  AOI22X1 g25933__2802(.A0 (\cache_data_way1[1] [14]), .A1 (n_199), .B0
       (cache_codeword[14]), .B1 (n_590), .Y (n_166));
  AOI22X1 g25934__1705(.A0 (\cache_data_way1[2] [15]), .A1 (n_192), .B0
       (\cache_data_way1[4] [15]), .B1 (n_178), .Y (n_165));
  AOI22X1 g25935__5122(.A0 (\cache_data_way1[3] [16]), .A1 (n_195), .B0
       (\cache_data_way0[1] [16]), .B1 (n_163), .Y (n_164));
  AOI22X1 g25936__8246(.A0 (\cache_data_way1[3] [17]), .A1 (n_195), .B0
       (\cache_data_way1[4] [17]), .B1 (n_178), .Y (n_162));
  AOI22X1 g25937__7098(.A0 (\cache_data_way1[3] [7]), .A1 (n_195), .B0
       (\cache_data_way0[1] [7]), .B1 (n_163), .Y (n_161));
  AOI22X1 g25938__6131(.A0 (\cache_data_way1[2] [18]), .A1 (n_192), .B0
       (\cache_data_way1[4] [18]), .B1 (n_178), .Y (n_160));
  AOI22X1 g25939__1881(.A0 (\cache_data_way1[1] [18]), .A1 (n_199), .B0
       (\cache_data_way0[4] [18]), .B1 (n_215), .Y (n_159));
  AOI22X1 g25940__5115(.A0 (\cache_data_way1[3] [2]), .A1 (n_195), .B0
       (\cache_data_way0[1] [2]), .B1 (n_163), .Y (n_158));
  AOI22X1 g25941__7482(.A0 (\cache_data_way1[3] [19]), .A1 (n_195), .B0
       (\cache_data_way0[1] [19]), .B1 (n_163), .Y (n_157));
  AOI22X1 g25942__4733(.A0 (\cache_data_way1[1] [19]), .A1 (n_199), .B0
       (\cache_data_way0[4] [19]), .B1 (n_215), .Y (n_156));
  AOI22X1 g25943__6161(.A0 (\cache_data_way1[1] [5]), .A1 (n_199), .B0
       (\cache_data_way0[4] [5]), .B1 (n_215), .Y (n_155));
  AOI22X1 g25944__9315(.A0 (\cache_data_way1[2] [12]), .A1 (n_192), .B0
       (\cache_data_way1[4] [12]), .B1 (n_178), .Y (n_154));
  AOI22X1 g25945__9945(.A0 (\cache_data_way1[2] [20]), .A1 (n_192), .B0
       (\cache_data_way0[1] [20]), .B1 (n_163), .Y (n_153));
  AOI22X1 g25946__2883(.A0 (\cache_data_way1[3] [10]), .A1 (n_195), .B0
       (\cache_data_way0[1] [10]), .B1 (n_163), .Y (n_152));
  AOI22X1 g25947__2346(.A0 (\cache_data_way1[1] [20]), .A1 (n_199), .B0
       (cache_codeword[20]), .B1 (n_590), .Y (n_151));
  AOI22X1 g25948__1666(.A0 (\cache_data_way1[2] [21]), .A1 (n_192), .B0
       (\cache_data_way0[1] [21]), .B1 (n_163), .Y (n_150));
  AOI22X1 g25949__7410(.A0 (\cache_data_way1[1] [21]), .A1 (n_199), .B0
       (\cache_data_way0[2] [21]), .B1 (n_217), .Y (n_149));
  AOI22X1 g25950__6417(.A0 (\cache_data_way1[1] [22]), .A1 (n_199), .B0
       (cache_codeword[22]), .B1 (n_590), .Y (n_148));
  AOI22X1 g25951__5477(.A0 (\cache_data_way1[2] [23]), .A1 (n_192), .B0
       (\cache_data_way0[1] [23]), .B1 (n_163), .Y (n_147));
  AOI22X1 g25952__2398(.A0 (\cache_data_way1[1] [23]), .A1 (n_199), .B0
       (\cache_data_way0[4] [23]), .B1 (n_215), .Y (n_146));
  AOI22X1 g25953__5107(.A0 (\cache_data_way1[2] [9]), .A1 (n_192), .B0
       (\cache_data_way1[4] [9]), .B1 (n_178), .Y (n_145));
  AOI22X1 g25954__6260(.A0 (\cache_data_way1[1] [6]), .A1 (n_199), .B0
       (cache_codeword[6]), .B1 (n_590), .Y (n_144));
  AOI22X1 g25955__4319(.A0 (\cache_data_way1[2] [8]), .A1 (n_192), .B0
       (\cache_data_way0[1] [8]), .B1 (n_163), .Y (n_143));
  AOI22X1 g25956__8428(.A0 (\cache_data_way1[1] [9]), .A1 (n_199), .B0
       (cache_codeword[9]), .B1 (n_590), .Y (n_142));
  AOI22X1 g25957__5526(.A0 (\cache_data_way1[1] [8]), .A1 (n_199), .B0
       (cache_codeword[8]), .B1 (n_590), .Y (n_141));
  AOI22X1 g25958__6783(.A0 (\cache_data_way1[2] [6]), .A1 (n_192), .B0
       (\cache_data_way0[1] [6]), .B1 (n_163), .Y (n_140));
  AOI22X1 g25959__3680(.A0 (\cache_data_way1[1] [3]), .A1 (n_199), .B0
       (\cache_data_way0[3] [3]), .B1 (n_209), .Y (n_139));
  AOI22X1 g25960__1617(.A0 (\cache_data_way1[2] [5]), .A1 (n_192), .B0
       (\cache_data_way0[1] [5]), .B1 (n_163), .Y (n_138));
  INVX1 g25981(.A (n_136), .Y (n_137));
  OAI2BB1X1 g25877__2802(.A0N (\cache_data_way0[4] [11]), .A1N (n_215),
       .B0 (n_100), .Y (n_135));
  OAI2BB1X1 g25883__1705(.A0N (\cache_data_way1[1] [17]), .A1N (n_199),
       .B0 (n_98), .Y (n_134));
  AND2X2 g25996__8246(.A (n_131), .B (n_133), .Y (n_241));
  AND2X2 g25997__7098(.A (n_84), .B (n_133), .Y (n_247));
  AND2X2 g25998__6131(.A (n_132), .B (n_133), .Y (n_245));
  AND2X2 g25999__1881(.A (n_132), .B (n_130), .Y (n_248));
  AND2X2 g25995__5115(.A (n_131), .B (n_130), .Y (n_246));
  NAND2X1 g25972__7482(.A (\cache_data_way1[4] [6]), .B (n_178), .Y
       (n_129));
  OAI2BB1X1 g25890__4733(.A0N (\cache_data_way0[2] [22]), .A1N (n_217),
       .B0 (n_87), .Y (n_128));
  OAI2BB1X1 g25876__6161(.A0N (\cache_data_way0[3] [9]), .A1N (n_209),
       .B0 (n_91), .Y (n_127));
  OAI2BB1X1 g25878__9315(.A0N (\cache_data_way0[3] [12]), .A1N (n_209),
       .B0 (n_90), .Y (n_126));
  NAND2X1 g25961__9945(.A (\cache_data_way1[3] [14]), .B (n_195), .Y
       (n_125));
  NAND2X1 g25962__2883(.A (\cache_data_way1[3] [4]), .B (n_195), .Y
       (n_124));
  NAND2X1 g25963__2346(.A (\cache_data_way1[2] [1]), .B (n_192), .Y
       (n_123));
  NAND2X1 g25964__1666(.A (\cache_data_way1[4] [2]), .B (n_178), .Y
       (n_122));
  NAND2X1 g25965__7410(.A (\cache_data_way1[4] [8]), .B (n_178), .Y
       (n_121));
  NAND2X1 g25966__6417(.A (\cache_data_way1[4] [7]), .B (n_178), .Y
       (n_120));
  NAND2X1 g25967__5477(.A (\cache_data_way1[2] [11]), .B (n_192), .Y
       (n_119));
  NAND2X1 g25968__2398(.A (\cache_data_way1[3] [12]), .B (n_195), .Y
       (n_118));
  NAND2X1 g25969__5107(.A (\cache_data_way1[2] [13]), .B (n_192), .Y
       (n_117));
  NAND2X1 g25970__6260(.A (\cache_data_way1[4] [20]), .B (n_178), .Y
       (n_116));
  NAND2X1 g25971__4319(.A (\cache_data_way1[3] [15]), .B (n_195), .Y
       (n_115));
  OAI2BB1X1 g25880__8428(.A0N (\cache_data_way0[2] [14]), .A1N (n_217),
       .B0 (n_88), .Y (n_114));
  OAI2BB1X1 g25879__5526(.A0N (\cache_data_way0[3] [13]), .A1N (n_209),
       .B0 (n_89), .Y (n_113));
  NAND2X1 g25974__6783(.A (\cache_data_way1[4] [3]), .B (n_178), .Y
       (n_112));
  NAND2X1 g25975__3680(.A (\cache_data_way1[2] [17]), .B (n_192), .Y
       (n_111));
  NAND2X1 g25976__1617(.A (\cache_data_way1[3] [9]), .B (n_195), .Y
       (n_110));
  NAND2X1 g25977__2802(.A (\cache_data_way1[3] [18]), .B (n_195), .Y
       (n_109));
  NAND2X1 g25978__1705(.A (\cache_data_way1[4] [19]), .B (n_178), .Y
       (n_108));
  NAND2X1 g25973__5122(.A (\cache_data_way1[4] [16]), .B (n_178), .Y
       (n_107));
  NAND2X1 g25982__8246(.A (\cache_data_way1[4] [5]), .B (n_178), .Y
       (n_106));
  NAND2X1 g25983__7098(.A (\cache_data_way1[4] [23]), .B (n_178), .Y
       (n_105));
  NAND2X1 g25984__6131(.A (\cache_data_way1[4] [10]), .B (n_178), .Y
       (n_104));
  NAND2X1 g25987__1881(.A (\cache_data_way1[4] [21]), .B (n_178), .Y
       (n_103));
  NAND2X1 g25988__5115(.A (\cache_data_way1[2] [22]), .B (n_192), .Y
       (n_102));
  NOR2XL g25992__7482(.A (address[5]), .B (n_94), .Y (n_136));
  DFFRHQX2 cache_hit_reg_reg(.RN (n_272), .CK (clk), .D
       (cache_hit_int), .Q (hit));
  OAI21XL g25993__4733(.A0 (write_en), .A1 (n_67), .B0 (n_92), .Y
       (n_250));
  AOI222X1 g25907__9315(.A0 (\cache_data_way0[4] [15]), .A1 (n_215),
       .B0 (\cache_data_way0[1] [15]), .B1 (n_163), .C0
       (cache_codeword[15]), .C1 (n_590), .Y (n_101));
  AOI222X1 g25903__9945(.A0 (\cache_data_way0[2] [11]), .A1 (n_217),
       .B0 (\cache_data_way0[1] [11]), .B1 (n_163), .C0
       (cache_codeword[11]), .C1 (n_590), .Y (n_100));
  AOI222X1 g25895__2883(.A0 (\cache_data_way0[4] [1]), .A1 (n_215), .B0
       (\cache_data_way0[1] [1]), .B1 (n_163), .C0 (cache_codeword[1]),
       .C1 (n_590), .Y (n_99));
  AOI222X1 g25909__2346(.A0 (\cache_data_way0[4] [17]), .A1 (n_215),
       .B0 (\cache_data_way0[1] [17]), .B1 (n_163), .C0
       (cache_codeword[17]), .C1 (n_590), .Y (n_98));
  AOI222X1 g25910__1666(.A0 (\cache_data_way0[2] [18]), .A1 (n_217),
       .B0 (\cache_data_way0[1] [18]), .B1 (n_163), .C0
       (cache_codeword[18]), .C1 (n_590), .Y (n_97));
  DFFRHQX2 \cache_valid_way0_reg[1] (.RN (n_272), .CK (clk), .D (n_78),
       .Q (\cache_valid_way0[1] ));
  AOI222X1 g25918__7410(.A0 (\cache_data_way0[3] [4]), .A1 (n_209), .B0
       (\cache_data_way0[1] [4]), .B1 (n_163), .C0 (cache_codeword[4]),
       .C1 (n_590), .Y (n_96));
  INVX1 g26001(.A (n_93), .Y (n_130));
  INVX1 g26002(.A (n_92), .Y (n_133));
  OR2X2 g26014__6417(.A (n_75), .B (n_79), .Y (n_213));
  AO21X2 g25994__5477(.A0 (n_73), .A1 (n_76), .B0 (n_70), .Y (n_214));
  DFFRHQX2 cache_hit_int_reg(.RN (n_272), .CK (clk), .D (n_86), .Q
       (cache_hit_int));
  AOI222X1 g25901__2398(.A0 (\cache_data_way0[4] [9]), .A1 (n_215), .B0
       (\cache_data_way0[1] [9]), .B1 (n_163), .C0
       (\cache_data_way0[2] [9]), .C1 (n_217), .Y (n_91));
  AOI222X1 g25904__5107(.A0 (\cache_data_way0[4] [12]), .A1 (n_215),
       .B0 (\cache_data_way0[1] [12]), .B1 (n_163), .C0
       (\cache_data_way0[2] [12]), .C1 (n_217), .Y (n_90));
  AOI222X1 g25905__6260(.A0 (\cache_data_way0[4] [13]), .A1 (n_215),
       .B0 (\cache_data_way0[1] [13]), .B1 (n_163), .C0
       (\cache_data_way0[2] [13]), .C1 (n_217), .Y (n_89));
  AOI222X1 g25906__4319(.A0 (\cache_data_way0[1] [14]), .A1 (n_163),
       .B0 (\cache_data_way0[3] [14]), .B1 (n_209), .C0
       (\cache_data_way0[4] [14]), .C1 (n_215), .Y (n_88));
  AOI222X1 g25916__8428(.A0 (\cache_data_way0[1] [22]), .A1 (n_163),
       .B0 (\cache_data_way0[3] [22]), .B1 (n_209), .C0
       (\cache_data_way0[4] [22]), .C1 (n_215), .Y (n_87));
  NAND2BX1 g26007__5526(.AN (n_85), .B (write_en), .Y (n_92));
  NOR2XL g26009__6783(.A (write_en), .B (n_86), .Y (n_94));
  NAND2X1 g26006__3680(.A (write_en), .B (n_85), .Y (n_93));
  AND2X2 g26010__1617(.A (n_66), .B (n_83), .Y (n_199));
  AND2X2 g26011__2802(.A (n_84), .B (n_83), .Y (n_195));
  AND2X2 g26012__1705(.A (n_132), .B (n_83), .Y (n_192));
  AND2X2 g26013__5122(.A (n_131), .B (n_83), .Y (n_178));
  AOI22X1 g25985__8246(.A0 (\cache_data_way0[3] [17]), .A1 (n_209), .B0
       (\cache_data_way0[2] [17]), .B1 (n_217), .Y (n_82));
  AOI22X1 g25986__7098(.A0 (\cache_data_way0[3] [16]), .A1 (n_209), .B0
       (\cache_data_way0[2] [16]), .B1 (n_217), .Y (n_81));
  AOI22X1 g25989__6131(.A0 (\cache_data_way0[3] [15]), .A1 (n_209), .B0
       (\cache_data_way0[2] [15]), .B1 (n_217), .Y (n_80));
  INVX1 g26021(.A (n_85), .Y (n_79));
  NAND2BX1 g26017__1881(.AN (\cache_valid_way0[1] ), .B (n_582), .Y
       (n_78));
  AOI22X1 g25990__5115(.A0 (\cache_data_way0[3] [1]), .A1 (n_209), .B0
       (\cache_data_way0[2] [1]), .B1 (n_217), .Y (n_77));
  DFFRHQX2 \cache_valid_way1_reg[1] (.RN (n_272), .CK (clk), .D (n_71),
       .Q (\cache_valid_way1[1] ));
  AOI2BB1X1 g26018__7482(.A0N (n_46), .A1N (n_74), .B0 (n_75), .Y
       (n_76));
  INVX1 g26022(.A (n_590), .Y (n_86));
  OAI21XL g26023__4733(.A0 (n_54), .A1 (n_74), .B0 (n_73), .Y (n_85));
  AND3XL g26024__6161(.A (read_en), .B (n_74), .C (n_73), .Y (n_83));
  OR2X1 g26016__9315(.A (\cache_valid_way1[1] ), .B (n_70), .Y (n_71));
  AND2X2 g26019__2346(.A (n_131), .B (n_67), .Y (n_215));
  AND2X2 g26020__1666(.A (n_84), .B (n_67), .Y (n_209));
  AND2X2 g26025__7410(.A (n_66), .B (n_67), .Y (n_163));
  AND2X2 g26026__6417(.A (n_132), .B (n_67), .Y (n_217));
  AND4XL g26031__5477(.A (n_15), .B (n_42), .C (n_59), .D (n_73), .Y
       (n_70));
  INVX1 g26033(.A (n_68), .Y (n_74));
  NOR2X1 g26029__2398(.A (n_64), .B (n_73), .Y (n_67));
  OAI21XL g26034__5107(.A0 (address[1]), .A1 (n_62), .B0 (n_63), .Y
       (n_68));
  OR4X1 g26032__6260(.A (n_47), .B (n_44), .C (n_48), .D (n_60), .Y
       (n_73));
  AOI211XL g26035__4319(.A0 (address[1]), .A1 (n_62), .B0 (n_49), .C0
       (n_61), .Y (n_63));
  OAI211X1 g26036__8428(.A0 (address[2]), .A1 (n_57), .B0 (n_53), .C0
       (n_58), .Y (n_61));
  OAI211X1 g26037__5526(.A0 (address[1]), .A1 (n_55), .B0 (n_59), .C0
       (n_56), .Y (n_60));
  AOI21XL g26041__6783(.A0 (address[2]), .A1 (n_57), .B0 (n_50), .Y
       (n_58));
  AOI21XL g26042__3680(.A0 (address[1]), .A1 (n_55), .B0 (n_51), .Y
       (n_56));
  AOI21XL g26043__1617(.A0 (n_53), .A1 (n_45), .B0 (n_52), .Y (n_54));
  XOR2X1 g26038__2802(.A (n_29), .B (n_40), .Y (n_238));
  XOR2X1 g26039__1705(.A (n_10), .B (n_41), .Y (n_243));
  XOR2X1 g26040__5122(.A (n_31), .B (n_38), .Y (n_236));
  XNOR2X1 g26049__8246(.A (address[2]), .B (n_33), .Y (n_51));
  XNOR2X1 g26048__7098(.A (address[4]), .B (n_34), .Y (n_50));
  XNOR2X1 g26044__6131(.A (address[3]), .B (n_36), .Y (n_49));
  XNOR2X1 g26050__1881(.A (address[3]), .B (n_35), .Y (n_48));
  NOR2XL g26053__5115(.A (address[4]), .B (n_43), .Y (n_47));
  NOR2XL g26054__7482(.A (n_52), .B (n_45), .Y (n_46));
  AND2X1 g26055__4733(.A (address[4]), .B (n_43), .Y (n_44));
  INVX1 g26056(.A (n_42), .Y (n_53));
  INVX1 g26057(.A (n_52), .Y (n_59));
  XOR2X1 g26052__6161(.A (data_in[12]), .B (n_39), .Y (n_41));
  XOR2X1 g26045__9315(.A (n_25), .B (n_39), .Y (n_40));
  XNOR2X1 g26051__9945(.A (data_in[10]), .B (n_37), .Y (n_38));
  AOI221X1 g26059__2883(.A0 (n_84), .A1 (\cache_addr_way0[3] [4]), .B0
       (n_131), .B1 (\cache_addr_way0[4] [4]), .C0 (n_16), .Y (n_43));
  AOI221X1 g26058__2346(.A0 (n_84), .A1 (\cache_lru[3] ), .B0 (n_131),
       .B1 (\cache_lru[4] ), .C0 (n_22), .Y (n_45));
  AOI221X1 g26060__1666(.A0 (n_84), .A1 (\cache_addr_way1[3] [2]), .B0
       (n_131), .B1 (\cache_addr_way1[4] [2]), .C0 (n_28), .Y (n_57));
  XOR2X1 g26046__7410(.A (data_in[1]), .B (n_37), .Y (n_244));
  XOR2X1 g26047__6417(.A (n_11), .B (n_30), .Y (n_242));
  AOI221X1 g26069__5477(.A0 (n_131), .A1 (\cache_addr_way1[4] [3]), .B0
       (n_84), .B1 (\cache_addr_way1[3] [3]), .C0 (n_21), .Y (n_36));
  AOI221X1 g26064__2398(.A0 (n_131), .A1 (\cache_addr_way0[4] [3]), .B0
       (n_84), .B1 (\cache_addr_way0[3] [3]), .C0 (n_20), .Y (n_35));
  AOI221X1 g26062__5107(.A0 (n_131), .A1 (\cache_addr_way1[4] [4]), .B0
       (n_84), .B1 (\cache_addr_way1[3] [4]), .C0 (n_32), .Y (n_34));
  AOI221X1 g26068__6260(.A0 (n_131), .A1 (\cache_addr_way0[4] [2]), .B0
       (n_84), .B1 (\cache_addr_way0[3] [2]), .C0 (n_23), .Y (n_33));
  AOI221X1 g26061__4319(.A0 (n_84), .A1 (\cache_addr_way1[3] [1]), .B0
       (n_131), .B1 (\cache_addr_way1[4] [1]), .C0 (n_17), .Y (n_62));
  AOI221X1 g26063__8428(.A0 (n_84), .A1 (\cache_addr_way0[3] [1]), .B0
       (n_131), .B1 (\cache_addr_way0[4] [1]), .C0 (n_19), .Y (n_55));
  AOI221X1 g26065__5526(.A0 (n_84), .A1 (\cache_addr_way1[3] [5]), .B0
       (n_131), .B1 (\cache_addr_way1[4] [5]), .C0 (n_24), .Y (n_42));
  AOI221X1 g26066__6783(.A0 (n_84), .A1 (\cache_addr_way0[3] [5]), .B0
       (n_131), .B1 (\cache_addr_way0[4] [5]), .C0 (n_18), .Y (n_52));
  AO22XL g26077__3680(.A0 (n_66), .A1 (\cache_addr_way1[1] [4]), .B0
       (n_132), .B1 (\cache_addr_way1[2] [4]), .Y (n_32));
  XNOR2X1 g26070__1617(.A (n_8), .B (n_26), .Y (n_31));
  XOR2X1 g26071__2802(.A (n_6), .B (n_27), .Y (n_30));
  XNOR2X1 g26067__1705(.A (n_3), .B (n_9), .Y (n_29));
  AO22XL g26076__5122(.A0 (n_66), .A1 (\cache_addr_way1[1] [2]), .B0
       (n_132), .B1 (\cache_addr_way1[2] [2]), .Y (n_28));
  XNOR2X1 g26073__8246(.A (data_in[7]), .B (n_7), .Y (n_37));
  XOR2X1 g26072__7098(.A (n_2), .B (n_27), .Y (n_39));
  XNOR2X1 g26075__6131(.A (n_26), .B (n_25), .Y (n_240));
  XOR2X1 g26074__1881(.A (data_in[5]), .B (n_5), .Y (n_237));
  AO22XL g26078__5115(.A0 (n_66), .A1 (\cache_valid_way1[1] ), .B0
       (n_132), .B1 (\cache_addr_way1[2] [6]), .Y (n_24));
  AO22XL g26079__7482(.A0 (n_66), .A1 (\cache_addr_way0[1] [2]), .B0
       (n_132), .B1 (\cache_addr_way0[2] [2]), .Y (n_23));
  AO22XL g26080__4733(.A0 (n_66), .A1 (\cache_lru[1] ), .B0 (n_132),
       .B1 (\cache_lru[2] ), .Y (n_22));
  AO22XL g26081__6161(.A0 (n_66), .A1 (\cache_addr_way1[1] [3]), .B0
       (n_132), .B1 (\cache_addr_way1[2] [3]), .Y (n_21));
  AO22XL g26082__9315(.A0 (n_66), .A1 (\cache_addr_way0[1] [3]), .B0
       (n_132), .B1 (\cache_addr_way0[2] [3]), .Y (n_20));
  AO22XL g26083__9945(.A0 (n_66), .A1 (\cache_addr_way0[1] [1]), .B0
       (n_132), .B1 (\cache_addr_way0[2] [1]), .Y (n_19));
  AO22XL g26084__2883(.A0 (n_66), .A1 (\cache_valid_way0[1] ), .B0
       (n_132), .B1 (\cache_addr_way0[2] [6]), .Y (n_18));
  AO22XL g26085__2346(.A0 (n_66), .A1 (\cache_addr_way1[1] [1]), .B0
       (n_132), .B1 (\cache_addr_way1[2] [1]), .Y (n_17));
  AO22XL g26086__1666(.A0 (n_66), .A1 (\cache_addr_way0[1] [4]), .B0
       (n_132), .B1 (\cache_addr_way0[2] [4]), .Y (n_16));
  INVX1 g26087(.A (n_75), .Y (n_15));
  NAND2X1 g26092__7410(.A (write_en), .B (n_66), .Y (n_75));
  INVX1 g26101(.A (n_66), .Y (n_14));
  INVX1 g26106(.A (n_132), .Y (n_12));
  XNOR2X1 g26096__6417(.A (data_in[12]), .B (data_in[2]), .Y (n_11));
  XNOR2X1 g26090__5477(.A (data_in[14]), .B (data_in[1]), .Y (n_10));
  XNOR2X1 g26091__2398(.A (data_in[7]), .B (data_in[4]), .Y (n_9));
  XNOR2X1 g26088__5107(.A (data_in[4]), .B (data_in[14]), .Y (n_8));
  XNOR2X1 g26094__6260(.A (data_in[9]), .B (data_in[11]), .Y (n_7));
  XNOR2X1 g26095__4319(.A (data_in[13]), .B (data_in[9]), .Y (n_6));
  XOR2X1 g26089__8428(.A (data_in[14]), .B (data_in[8]), .Y (n_5));
  XOR2X1 g26093__5526(.A (data_in[13]), .B (data_in[8]), .Y (n_25));
  INVX1 g26102(.A (n_131), .Y (n_4));
  XNOR2X1 g26098__6783(.A (data_in[2]), .B (data_in[5]), .Y (n_3));
  XNOR2X1 g26097__3680(.A (data_in[6]), .B (data_in[16]), .Y (n_2));
  XNOR2X1 g26100__1617(.A (data_in[16]), .B (data_in[3]), .Y (n_26));
  XOR2X1 g26099__2802(.A (data_in[10]), .B (data_in[15]), .Y (n_27));
  AND2X1 g26107__1705(.A (address[5]), .B (n_1), .Y (n_84));
  AND2X1 g26103__5122(.A (n_1), .B (n_0), .Y (n_66));
  AND2X1 g26108__8246(.A (address[6]), .B (n_0), .Y (n_132));
  AND2X1 g26104__7098(.A (address[6]), .B (address[5]), .Y (n_131));
  INVX1 g26112(.A (address[5]), .Y (n_0));
  INVX1 g26110(.A (read_en), .Y (n_64));
  INVX1 g26111(.A (address[6]), .Y (n_1));
  INVX1 g26109(.A (rst), .Y (n_272));
  NAND2BX1 g2(.AN (n_75), .B (n_68), .Y (n_582));
  NOR2BX1 g26389(.AN (n_471), .B (n_420), .Y (n_583));
  OAI2BB2XL g26390(.A0N (n_489), .A1N (n_370), .B0 (n_449), .B1
       (n_421), .Y (n_584));
  NOR2BX1 g26391(.AN (n_383), .B (n_324), .Y (n_585));
  NAND2BX1 g26392(.AN (n_317), .B (n_330), .Y (n_586));
  NOR2BX1 g26393(.AN (n_449), .B (n_521), .Y (n_587));
  NAND2BX1 g26394(.AN (n_94), .B (address[5]), .Y (n_588));
  NAND3BXL g26395(.AN (n_209), .B (n_591), .C (n_223), .Y (n_589));
  AOI2BB1X4 g26396(.A0N (n_64), .A1N (n_68), .B0 (n_67), .Y (n_590));
  NAND2BX4 g26397(.AN (n_93), .B (n_84), .Y (n_591));
endmodule

